### ISSUE TITLE
Regarding accuracy of current Oklab matrix used in Color.js

### ISSUE THREAD

**Issue by facelessuser** [LeaVerou/color.js#109]
While playing with Okhsl and Okhsv, I noticed that the current XYZ matrix is not the best for Oklab.

The [implementation notes provide](https://bottosson.github.io/posts/oklab/#implementation) both conversions to/from XYZ D65 and Oklab and to/from sRGB Linear and Oklab.

What is interesting to note is this:

> The matrices were updated 2021-01-25. The new matrices have been derived using a higher precision sRGB matrix and with exactly matching D65 values. The old matrices are available here for reference. The values only differ after the first three decimals.

It appears that the XYZ matrices were not updated when the sRGB Linear matrices were. Or it appears that way as the results do differ. This is most noticeable around white. Color.js still uses the XYZ matrix:

```js
> new Color('white').to('oklab').coords
[
  0.9999998095202896,
  -0.000010091754967744837,
  -0.00008610878004533529
]
> new Color('white').to('oklch').coords
[ 0.9999998095202896, 0.00008669812869505855, NaN ]
```

Now, notice the results when using the sRGB linear matrices (I've currently implemented it in my library). Now, I didn't bother just using what he has but calculated the inverse matrix without the rounding he does so roundtrips are good.

```py
>>> Color('white').convert('oklab').coords()
[0.9999999934735462, 8.095285553011422e-11, 3.727390762708893e-08]
>>> Color('white').convert('oklch').coords()
[0.9999999934735462, 3.727399553519285e-08, nan]
```

Converting grayscale colors in RGB pretty far out `-0x600 - 0x600` used for the RGB channels. The distance of `a`, `b`, and `chroma` from 0 is found below:

```
oklab: maximum a: 0.00000000023776158819543979916488751769065856933593750
oklab: maximum b: 0.00000010947514450521111939451657235622406005859375000
oklch: maximum chroma: 0.00000010947540269398270465060779175689442688224062294
```

You could definitely relax the epsilon you currently use `ε = 0.0002`.

If going the route of adding Oklab\Oklch to the CSS spec, it may be best to use the matrix with the best results. With that said, if it is desired to have a direct conversion from XYZ D65 instead of passing through XYZ D50 -> sRGB Linear -> Oklab, then it may be possible, but I didn't bother to look into that much at this time.

Thought this info might be useful.

**Comment by facelessuser** [comment]
If there is any interest, I've recalculated all the matrices. This includes the sRGB Linear to LMS and the XYZ D65 to LMS.
The LMS \*\* 1/3 to Oklab are unchanged. This brings the XYZ matrices up to date with the recent sRGBL calculations. The latter isn't really needed unless there is interest in implementing Okhsl and Okhsv.

It's possible I brought this whole topic up before, but this is the first time I think I bothered to go through the effort to see the difference in results. And definitely the first time I bothered to recalculate the XYZ D65 matrix.

Obviously, if the old XYZ matrices are preferred, this can all be disregarded, but generally, the higher precision, new matrices seem to give better results. Personally, I'll be using these matrices as it is the only way to get clean Okhsl and Okhsv roundtrip values if using Oklab values calculated with the XYZ matrix (I guess one could use the older sRGBL matrices in Okhsl and Okhsv, but there is nothing to gain using the lower precision matrices).  The script is found here https://github.com/facelessuser/coloraide/blob/master/tools/calc_oklab_matrices.py. Calculations are based on the D65 values of 0.3127, 0.3290.

```
===== sRGB Linear => lms =====
[[0.4122214708 0.5363325363 0.0514459929]
 [0.2119034982 0.6806995451 0.1073969566]
 [0.0883024619 0.2817188376 0.6299787005]]
===== lms -> sRGB Linear =====
[[ 4.076741661347994    -3.3077115904081933    0.23096992872942793 ]
 [-1.2684380040921763    2.6097574006633715   -0.3413193963102196  ]
 [-0.004196086541837079 -0.7034186144594495    1.7076147009309446  ]]
===== XYZ D65 Linear => lms =====
[[ 0.8190224432164319   0.3619062562801221  -0.12887378261216417]
 [ 0.0329836671980271   0.9292868468965546   0.0361446681699984 ]
 [ 0.04817719956604624  0.2642395249442277   0.6335478258136936 ]]
===== lms -> XYZ D65 =====
[[ 1.2268798733741557  -0.5578149965554813   0.28139105017721594]
 [-0.04057576262431372  1.1122868293970594  -0.07171106666151696]
 [-0.07637294974672142 -0.4214933239627916   1.5869240244272422 ]]
===== lms ** 1/3 -> Oklab =====
[[ 0.2104542553  0.793617785  -0.0040720468]
 [ 1.9779984951 -2.428592205   0.4505937099]
 [ 0.0259040371  0.7827717662 -0.808675766 ]]
===== Oklab -> lms ** 1/3 =====
[[ 0.9999999984505196   0.39633779217376774  0.2158037580607588 ]
 [ 1.0000000088817607  -0.10556134232365633 -0.0638541747717059 ]
 [ 1.0000000546724108  -0.08948418209496574 -1.2914855378640917 ]]
```

**Comment by svgeesus** [comment]
Following discussion in CSSWG https://github.com/w3c/csswg-drafts/issues/6642 fixed by https://github.com/LeaVerou/color.js/commit/b7c04458ed779c246edd875f1d9feb8915223f30 for which my thanks
