### ISSUE TITLE
Linear RGB interpolation

### ISSUE THREAD

**Issue by LeaVerou** [LeaVerou/color.js#11]
@svgeesus says it's basically XYZ interpolation, which we do support, does that mean we don't need to do anything?

**Comment by svgeesus** [comment]
We now [have linear-light sRGB](https://github.com/LeaVerou/color.js/blob/master/src/spaces/srgb-linear.js).

Interpolating in linear-light sRGB and XYZ [gives the same result](https://colorjs.io/notebook/?storage=https%3A%2F%2Fgist.github.com%2Fsvgeesus%2F715b15e1c0a8d51ba37e26b82b494505)
