### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Olian04** [LeaVerou/color.js#119]
Are there any plans to support typescript when version 1.0 releases?

**Comment by LeaVerou** [comment]
We'd welcome PRs to add typings files, but it's pretty low priority to write such files ourselves.

**Comment by Olian04** [comment]
@LeaVerou may I ask why TypeScript support isn't a priority? It seems odd for a library of this proportion not to prioritize interoperability with other JavaScript "dialects", such as TypeScript. Especially seeing how popular TypeScript has become over the past few years.

**Comment by LeaVerou** [comment]
Only because time is finite 😊

**Comment by Olian04** [comment]
Would you be willing to document your code using [jsdoc](https://jsdoc.app/)? Because if you did then you could generate typescript declaration files from those jsdoc string using the typescript compiler. See https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html

**Comment by benmccann** [comment]
More discussion about this in https://github.com/LeaVerou/color.js/issues/168#issue-1288727750

**Comment by NatoBoram** [comment]
Personally, I'd vote for a full TypeScript makeover since it would benefit all JavaScript flavours, text editors, IDEs, linters and language servers simultaneously, but that's just me.

Is this something that you would find interesting?

**Comment by MysteryBlokHed** [comment]
I'm working on types for color.js right now on DefinitelyTyped/DefinitelyTyped#62510. I prefer DefinitelyTyped for definitions files because I think they have good infrastructure to test and maintain, but I could make a PR here instead if people want that.

If I continue on DefinitelyTyped, I could add any contributors here who are interested in maintaining those types to the list of owners. That way, you'd be automatically notified about changes to the types and be able to merge them.

**Comment by benmccann** [comment]
Including them here is much better because you can make sure they stay in sync. The types on DefinitelyTyped frequently don't get updated when the main package does. It's easy enough to setup the small amount of infrastructure required here

**Comment by MysteryBlokHed** [comment]
I'll work on moving the types to a PR over here. If maintainers are interested, I'll also try to configure a CI job to test the types with dtslint the way DefinitelyTyped does.

**Comment by MysteryBlokHed** [comment]
I just opened #221 to bring the types over from DefinitelyTyped, but I'm having trouble getting TypeScript and dtslint to work properly, at least on my local setup.
