### ISSUE TITLE
Error: self is not defined

### ISSUE THREAD

**Issue by siriwatknp** [LeaVerou/color.js#121]
First of all, thanks for creating this amazing color library.

### Issue

I am using NextJS `v10.0.0` with some custom `_document.tsx` and I found this error on the server-side. The usage is pretty simple:

```js
function Page() {
  const [bgColor, setBgColor] = React.useState(new Color(blue[100]));
  const backgroundColor = bgColor.toString() // crash!
  return (...)
}
```

![image](https://user-images.githubusercontent.com/18292247/150642991-cc18e2e1-0685-4f25-a157-c8f9aa3071fd.png)

**Comment by LeaVerou** [comment]
Hey, thanks for reporting. Did it have a stack trace that went down to Color.js so we can see what's the offending `self` reference?

**Comment by siriwatknp** [comment]
Does this help? let me know if you need more info.

![image](https://user-images.githubusercontent.com/18292247/150715045-7cbdb59a-bfc9-41ae-add2-58f88e9f326d.png)

**Comment by nurbo** [comment]
@siriwatknp: if you're running in a Node.js context the `self` is not defined.

For a temporary fix, you can create the alias `self` in `global`, like so:

```js
(function () {
  typeof self === 'undefined' && typeof global === 'object' ? global.self = global : null;
})()
```

Maybe it would've been better to use `globalThis` in the code instead of `self`.

**Comment by tomasIndicius** [comment]
@siriwatknp I just run into the same issue here. Any luck fixing it?

**Comment by LeaVerou** [comment]
Happy to merge PRs using `globalThis` instead of `self`

**Comment by siriwatknp** [comment]
> Happy to merge PRs using `globalThis` instead of `self`

will open a PR soon, thanks.

**Comment by LeaVerou** [comment]
Actually there doesn't seem to be any `self` in the source files. I think this may be a bug with the build tools?

**Comment by LeaVerou** [comment]
I think this must be fixed with the new release since it was related to #134, if not please reopen.

**Comment by tomasIndicius** [comment]
Seems to be fixed! Thanks!
