### ISSUE TITLE
npm package: `No color space found with id = "oklch"` error

### ISSUE THREAD

**Issue by ai** [LeaVerou/color.js#134]
```js
new Color('oklch', [0, 0, 0])
```

doesn’t work in npm package. `oklab` doesn’t work too, but `lch` works fine.

Did we have some OKLab plugin which was not installed into npm files?

**Comment by ai** [comment]
@LeaVerou what is the process to release npm package?

I found that `node_modules/colorjs.io/dist/color.cjs.js` is not equal to `color.js/dist/color.cjs.js` after calling `gulp bundle`.

**Comment by ai** [comment]
https://github.com/LeaVerou/color.js/issues/121 is also fixed if I am using `color.js/dist/color.cjs.js` from the repo.

Seems like we need to re-build `dist/` before making the release.

**Comment by matt123miller** [comment]
I came to create a similar issue, the problem being that the docs suggest colour spaces that aren't available in the latest version of the NPM package. Here's the spaces I have available in my webpage using version `0.0.5` where I use the default import in my code `import Color from 'colorjs.io';`

<img width="240" alt="Screenshot 2022-05-08 at 17 03 21" src="https://user-images.githubusercontent.com/9091121/167304738-3c1fb72d-adca-446e-9d84-f83612fcc4c6.png">

And here's what's available per the docs

<img width="569" alt="Screenshot 2022-05-08 at 17 03 09" src="https://user-images.githubusercontent.com/9091121/167304751-a77de642-373d-4dcf-a1a1-dcc1d39805a9.png">

There differences are:

- "xyz-d50"
- "xyz-d65"
- "srgb-linear"
- "rec2100pq"
- "oklab"
- "oklch"
- "acescc"

I agree with @ai in that performing a release would likely resolve the issue.

**Comment by LeaVerou** [comment]
I just published a new npm package, could you please check that this is fixed and reopen if not?

**Comment by jmz7v** [comment]
Just bumped into this issue, still trying to figure it out, I'll update my comment and potentially make a PR to the docs but still commenting the error so that it's easier to search:

Usage:
```
const palette = steps(
    color1,
    color2,
    {
      space: "lch",
      steps: 10,
    },
  );
```


Error:
```
Uncaught TypeError: No color space found with id = "lch"
```

Currently used as:
```
import Color from "colorjs.io";
```

via Vite.

**Comment by jgerigmeyer** [comment]
@jmz7v It's not recommended to combine the `Color` object API (`import Color from "colorjs.io";`) and the [procedural API](https://colorjs.io/docs/procedural) (`import { ... } from "colorjs.io/fn";`). When using `steps` from `colorjs.io/fn`, you need to register any required color spaces manually.

I think your example can be fixed by using `Color.steps(...)`, or by adding:

```js
import { ColorSpace, LCH, steps } from "colorjs.io/fn";

ColorSpace.register(LCH);
```
