### ISSUE TITLE
Finding the "opposite colour"

### ISSUE THREAD

**Issue by matt123miller** [LeaVerou/color.js#140]
Maybe this concept doesn't make sense in colour science, but I'm working on a little site to help me when painting miniatures to choose between available paints. I have an array of objects representing different paints with their hex values and names. I can then loop the array and attach values in different colours spaces to each object as needed.

```javascript
const paints = [
  {
    name: 'Kantor Blue',
    hexCode: '#02134E',
  },
  {
    name: 'Fyreslayer Flesh',
    hexCode: '#BD7866',
  },
  {
    name: 'Phalanx Yellow',
    hexCode: '#FFE200',
  }
]
```

I can use your [difference api](https://colorjs.io/docs/color-difference.html#delta-e-%CE%B4e) to find which paint is closest to any given other colour by finding the smallest difference value, that's really useful!

But I also want to find complimentary colours which in simple terms, from a painting perspective, is a colour on the opposite side of the colour wheel (see attached). Should I again use the [difference api](https://colorjs.io/docs/color-difference.html#delta-e-%CE%B4e) but find a paint with the largest difference value? Is there a more appropriate method of doing this?

![image](https://user-images.githubusercontent.com/9091121/163565007-a383ee7f-d3c7-40ba-b789-a95da9c6ff47.png)

**Comment by facelessuser** [comment]
I don't think using the difference API would be a good way to get complementary colors. To be honest, for colors in the sRGB gamut, most people just do something simple like add or subtract 180˚ in the HSL color space.

If you wanted Triadic colors, you'd add 120˚for one of the colors and subtract 120˚ for the other.

If you wanted split complementary colors, you could add 210˚ and subtract 210˚.

If you wanted analogous colors, you could add 30˚ and subtract 30˚.

if you wanted tetradic colors, you could subtract 120˚, 180˚, and 300˚.

At least that is how a lot of online calculators do this 🙂.

**Comment by facelessuser** [comment]
I would add, if you check out https://en.wikipedia.org/wiki/Complementary_colors, it states that two complementary colors add up to equal white. So one could argue you could calculate complementary by subtracting each channel of color from white to get its complimentary. This is a different approach than you'll see in most online calculators and is probably a more faithful implementation than just rotating the hue, but I imagine you are looking for what you've seen in most places. But if not, you can give this a try.

**Comment by matt123miller** [comment]
Thanks @facelessuser for the detailed response. I'll try rotating in HSL space like you suggest. I did some research a few months back and tried to roll my own stuff but never got very far. Glad I found a library like this 😄 

For reference [this is the WIP webpage](https://www.matt123miller.dev/paint-mixer-app/) in question. I got something kind of working using the difference API earlier before I saw this response. I'll get around to trying your suggestion over the next few days.

**Comment by facelessuser** [comment]
Yeah, it may be possible to do something with the differencing API, but that seems like a labor-intensive approach. For true complementary color, it seems subtracting the color from white would give you the exact complementary color. Most people are actually satisfied with just the complementary hue (keeping saturation and lightness in HSL constant). It really just depends on what your goals are.

You can see a lot places they are just showing the complementary hue: https://www.sessions.edu/color-calculator/

**Comment by LeaVerou** [comment]
A polar space, yes, but please don't do operations in HSL. LCH or OKLCH would be great for this.

**Comment by facelessuser** [comment]
> A polar space, yes, but please don't do operations in HSL. LCH or OKLCH would be great for this.

Certainly, colors will be a bit different from observable examples on the web, but results will be performed in a more perceptually uniform space 🙂.

**Comment by matt123miller** [comment]
> A polar space, yes, but please don't do operations in HSL. LCH or OKLCH would be great for this.

Should I work in LCH or OKLCH spaces for all computations but then convert to hex values or [CSS 3 colours](https://caniuse.com/css3-colors) for displaying colours universally across browsers? I don't know anything about colour science...

**Comment by facelessuser** [comment]
I'm not sure about all the calculations you are doing. If we are talking just complementary colors, then yeah, you can convert them to a polar space, perform your calculation, and then display them in RGB.

>  I don't know anything about colour science...

You don't have to know much about colour science to use colours 🙂. The main reason that LCH and Oklch are suggested to be used instead of HSL is simply because LCH and Oklch are designed to be more perceptually uniform. For instance, HSL doesn't do so well with perceived lightness (and other things).

**Comment by matt123miller** [comment]
Little later than planned but I implemented what I think finds the complimentary colour. Here's the gist of it.
```javascript
const lchWhite = new Color('lch', [100, 150, 360]);

export function findComplimentaryColour(colour: Color): Color {
  const lch = colour.to('lch');
  lch.lch.hue = lchWhite.hue - lch.lch.hue;
  return lch;
}
```

And [here's the site it's being used in](https://www.matt123miller.dev/paint-mixer-app/). Very ugly currently but now I've done the "main feature" I can work on that 😁 

If you believe I've accomplished what I set out to do, colour wise, then feel free to close the issue.

**Comment by facelessuser** [comment]
@matt123miller, I'm not sure your algorithm is correct. As mentioned earlier, all you need to do is rotate the hue 180˚ on the color wheel to get color on the opposite side. Right now, you are subtracting every angle from 360, so the colors are not correct.

Maybe this will help. I maintain a color library written in Python, and this conversation inspired me to add color harmony support. I wrote up a page describing things a bit more and demonstrating how it works. I see you've chosen to use Lch, though my examples will be using Oklch. You can can actually override the examples in the page live and use Lch. Hopefully, it helps describe things a bit more.

https://facelessuser.github.io/coloraide/harmonies/

**Comment by svgeesus** [comment]
> `lch.lch.hue = lchWhite.hue - lch.lch.hue;`

A white (or in general any gray) will not have a defined hue. As @facelessuser said, in `lch` or (better) in `oklch` add 180 to the hue of your color to get the complementary.

**Comment by svgeesus** [comment]
```js

export function findComplimentaryColour(colour: Color): Color {
  const lch = colour.to('lch');
  lch.lch.hue += 180;
  return lch;
}
