### ISSUE TITLE
Question: Relative hue brightness

### ISSUE THREAD

**Issue by msikma** [LeaVerou/color.js#142]
Hi there. I'm using color.js to generate unique colors per username in a chatroom. Basically I'm picking a random hue (in `lch` colorspace) based on the user's name and then displaying their chat message with that color after converting it to rgb values.

However, an issue I'm running into is that bright colors like yellow are too dark on lightness 50%, and dark colors like blue are a bit too bright on it. I'd like to be able to correct the value based on the perceptual brightness of the hue, but I haven't been able to figure out how to do that.

Is there a way to do this, either through using a different colorspace or by some other method?

For the record, here's more or less what I'm doing:

```js
const getUserColor = username => {
  const hue = getRandomIntBySeed(username, 0, 360) // 0, 360 are min/max values
  const lum = getRandomIntBySeed(username, 50, 70)
  const c = new Color('lch', [lum, 100, hue])
  return c.to('srgb').toString() // this gets set as a style tag on an element
}
```

I appreciate any tips!

**Comment by msikma** [comment]
OK, I think I figured it out. I actually just shouldn't have tried to do this with the `lch` colorspace. If I use the `hsl` colorspace all colors are nice and bright and have luminance according to the relative brightness of the color.

I'll close since this answers my question and this might be useful for other people to read.

**Comment by LeaVerou** [comment]
LCH doesn't work like HSL. 50% lightness is actually 50% lightness, whereas HSL is all over the place and yellow and blue have the same lightness. Not sure what you need exactly, but gamut mapping may also be at play, since LCH can express any visible color, whereas HSL can only express sRGB colors.
