### ISSUE TITLE
Use .mjs extension for ESM build.

### ISSUE THREAD

**Issue by jgerigmeyer** [LeaVerou/color.js#155]
Build tools that use native ESM (e.g. Vite) expect ESM builds to use the `.mjs` extension (unless the nearest `package.json` has `"type": "module"`, in which case CJS builds should use the `.cjs` extension).

See: https://nodejs.org/api/packages.html#determining-module-system

Currently, both the ESM and CJS builds use `.js` -- this causes Node to assume they are both CJS:

> Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.

Would you be willing to consider either adding `"type": "module"` to your `package.json` file, or renaming the built packages to e.g. `color.esm.mjs` and `color.cjs.js`?

**Comment by LeaVerou** [comment]
Thank you for pointing that out! I just pushed a fix that:

- Renames CJS exports to use `.cjs`
- Adds `type: "module"` to `package.json`
- Makes `color.js` be the ESM version (IIFE is now `color.iife.js`)

Let me know if that fixes it!

**Comment by LeaVerou** [comment]
I had to revert `type: "module"` because it broke eleventy :( Hopefully the `.cjs` extension fixes it though?

**Comment by LeaVerou** [comment]
Nevermind, it was the eleventy config. I re-added `type: "module"`. The last 2 messages will self-destruct in 3, 2, 1…

**Comment by jgerigmeyer** [comment]
> Let me know if that fixes it!

Works for me, testing locally! I noted a few minor issues:

1. It looks like the `main` and `module` paths in `package.json` need to be updated to the newer build.
2. ~~You may run into trouble compiling the 11ty site with `"type": "module"` set.~~ Looks like you already solved this 🎉 
3. Similarly, I think `postcss.config.js` needs to be renamed to `.cjs` for `npm run build:css` to work.

**Comment by LeaVerou** [comment]
> > Let me know if that fixes it!
> 
> Works for me, testing locally! I noted a few minor issues:
> 
> 1. It looks like the `main` and `module` paths in `package.json` need to be updated to the newer build.
> 2. ~You may run into trouble compiling the 11ty site with `"type": "module"` set.~ Looks like you already solved this 🎉
> 3. Similarly, I think `postcss.config.js` needs to be renamed to `.cjs` for `npm run build:css` to work.

I forgot to post yesterday, all of these should be fixed now!
