### ISSUE TITLE
OKlab & OKlch interpolation support

### ISSUE THREAD

**Issue by NateBaldwinDesign** [LeaVerou/color.js#185]
## Description
Add OKLab and OKLch support to interpolation functions `.range()` and `.step()`

## Details
When using `.range()` or `.steps()`, both "oklab" and "oklch" throw an error as an unsupported color space. 

```
color.js:765 Uncaught TypeError: No color space found with id = "oklab"
```
```
color.js:765 Uncaught TypeError: No color space found with id = "oklch"
```

## Motivation
As a designer, I would like to leverage these color spaces as options for interpolation when generating colors.

**Comment by LeaVerou** [comment]
Hi Nate,

These functions already support oklab and oklch, they're written in a way that they don't need to "support" any color space in particular, as long as a color space is available, it can be used. I suspect these color spaces have just not been loaded.
Can you share how you are including Color.js?

**Comment by svgeesus** [comment]
Confirming that interpolation in OKLab is supported: here is the [gradient app](https://colorjs.io/apps/gradients/) interpolating in OKLab

![image](https://user-images.githubusercontent.com/2506926/176908098-f01dbec9-6c08-4aa5-9bee-02c6086c93d8.png)

**Comment by LeaVerou** [comment]
Hi Nate, it's very hard to figure out why your Color.js doesn't include OKLab/OKLCh without the answer to my previous question:

> Can you share how you are including Color.js?

**Comment by NateBaldwinDesign** [comment]
Sorry yes:

```js
import Color from "colorjs.io";

colorSpaces = [
      'lab',
      'lch',
      'oklab',
      'oklch',
      'rgb',
      'hsl'
    ];

colorSpaces.map((space) => {
    const color1 = new Color('#ff8002');
    const color2 = new Color('#1ca9e6');
    let colors = color1.steps(color2, {
      space: space,
      outputSpace: "srgb",
      maxDeltaE: 3, // max deltaE between consecutive steps
      steps: 10 // min number of steps
    });

    return <div className="gradientRamp" style=`background-image: linear-gradient(90deg, ${colors})`></div>
})

**Comment by LeaVerou** [comment]
Thanks! And how are you running it? Are you using a bundler, running it in Node etc?

**Comment by NateBaldwinDesign** [comment]
Using Node

**Comment by LeaVerou** [comment]
There are many syntax errors in the code above and also it references a nonexistent `"rgb"` space (I assume you meant `"srgb"`). Once I fixed it it works fine in a fresh install:

```js
import Color from "colorjs.io";

let colorSpaces = [
      'lab',
      'lch',
      'oklab',
      'oklch',
      'srgb',
      'hsl'
    ];

let a = colorSpaces.map((space) => {
    const color1 = new Color('#ff8002');
    const color2 = new Color('#1ca9e6');
    let colors = color1.steps(color2, {
      space: space,
      outputSpace: "srgb",
      maxDeltaE: 3, // max deltaE between consecutive steps
      steps: 10 // min number of steps
    });

    return `<div className="gradientRamp" style="background-image: linear-gradient(90deg, ${colors})"></div>`;
});

console.log(a);
```

can you try it out and let me know?

**Comment by NateBaldwinDesign** [comment]
I'll check this out, thanks
