### ISSUE TITLE
Access to representation of a color space transform?

### ISSUE THREAD

**Issue by donmccurdy** [LeaVerou/color.js#188]
I'm not sure if this is fairly within scope of the color.js project, but I'd love to be able to generate and access a machine-readable representation of the transform between two color spaces. Given a color in a known color space it's exciting to be able to quickly convert the color ...

```js
ColorSpace.get(fromSpace).to(toSpace, coords); // {coords: [1.0, 0.0, 0.0]}
```

... but would an abstract representation of the transform itself be feasible? Something like:

```js
ColorSpace.get(fromSpace).toTransform(toSpace); // {matrix: [1, 2, 3, ...]}
```

I'm trying to think through use of color.js in WebGL applications, where it's necessary to delegate conversion to a pixel shader to do realtime conversions for input textures or the output canvas. Just wondering how many such transforms can be represented as a 3x3 matrix, or maybe a 1D or 3D LUT is required — would love to get your thoughts on the idea. Thanks!

**Comment by LeaVerou** [comment]
Hmmm what if `ColorSpace#to(space)` returned a function? Would that work?

**Comment by donmccurdy** [comment]
Unfortunately, I can't programmatically convert a JavaScript function to GLSL code for the WebGL use case. OpenColorIO configs use declarative representations of transforms (https://opencolorio.readthedocs.io/en/latest/api/transforms.html). Those seem to be meant for use by their SDK but I've had some luck reverse-engineering them ([example](https://github.com/donmccurdy/three-filmic/blob/8a9bae5b70d73a519b29425eda1283fe2bbff075/src/FilmicPass.ts#L95-L106)). 

Generating a lookup table (say N=1024 samples) could probably be done in userland without changes to color.js, and GLSL code can sample from that. With some assumptions about the input/output domains this is probably manageable, maybe limited to spaces using the RGB color model.

Thanks for the pointer to `toBase` / `fromBase`! The number of color spaces I'd use in a WebGL application is probably limited, so just being able to reference code in this project is also really helpful. :)

**Comment by LeaVerou** [comment]
Ok, then I guess I'm gonna close this. Glad I could help!
