### ISSUE TITLE
`parse()` should trim input strings

### ISSUE THREAD

**Issue by AlainGourves** [LeaVerou/color.js#196]
This leads to a TypeError:

```js
let c = " #bada55"; // Notice the leading space
let color = new Color(c);
```
There's the same problem with CSS named colors, leading or trailing spaces produce errors. 
So it might be a good idea to trim the inputs before parsing, to make the library idiot proof ? 

Otherwise fantastic library !

**Comment by LeaVerou** [comment]
Sure, sounds good! This should be a very easy PR for any new contributors, so I'll leave it up for grabs :)

**Comment by LeaVerou** [comment]
And thanks for the kind words! ❤️

**Comment by AlainGourves** [comment]
@LeaVerou  could it be as easy as modifying `parse.js` like that ?
(I'm not familiar with complex project like this one)

```js 
export default function parse (str) {
	let env = {"str": str.trim()};
	// ...
```

**Comment by LeaVerou** [comment]
Yup, pretty much! 😄

**Comment by LeaVerou** [comment]
I'd do `str?.trim()` to avoid errors in case
