### ISSUE TITLE
How to generate rgba from any color?

### ISSUE THREAD

**Issue by jcubic** [LeaVerou/color.js#202]
I have code like this:

```javascript
const color = new Color(declaration.value);
color.set({
   alpha: 0.997
});
const value = color.to('hex');
```

where declaration.value is any color (most of the time hex without alpha) and I want to add alpha to that color and generate rgba.

But got error:
> TypeError: No "alpha" coordinate found in sRGB. Its coordinates are: r, g, b

Also, rgba is not supported. Is there a way to generate rgba from any color for CSS property?

**Comment by facelessuser** [comment]
You can do:

```
color.alpha = 0.997
```

I'm not sure why you can't set `alpha` with `set()`...it may be the intention that `set` was only for "color" components, and not for the alpha component, but I'm not sure the reason for that restriction.

**Comment by jcubic** [comment]
@facelessuser thanks, this work.

**Comment by LeaVerou** [comment]
FWIW I would be fine merging a PR to set alpha from `set()` as well!
