### ISSUE TITLE
Website: Remove note regarding open issue about treeshaking

### ISSUE THREAD

**Issue by lydell** [LeaVerou/color.js#204]
This note is on https://colorjs.io/docs/spaces.html:

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/2142817/184683097-7baba9fb-d97a-4044-ba9c-f85c64b3c7b7.png">

It links to https://github.com/LeaVerou/color.js/issues/163 – which has since been closed! 🎉 

The note can be removed now.

Issue extracted from https://github.com/LeaVerou/color.js/issues/163#issuecomment-1215226412

**Comment by LeaVerou** [comment]
Thanks!
