### ISSUE TITLE
Avoid Nullish coalescing operator to support old Node.js

### ISSUE THREAD

**Issue by ai** [LeaVerou/color.js#205]
We are adding `color.js` to Stylelint for cool [`color-no-out-gamut-range`](https://github.com/stylelint/stylelint/pull/6271) rule.

But `??` operator from `color.js` sources breaks Node.js 12 and 14 support:

```
    /home/runner/work/stylelint/stylelint/node_modules/colorjs.io/dist/color.cjs:328
    		let coords = options.coords ?? this.base.coords;
    		                             ^

    SyntaxError: Unexpected token '?'
```

**Comment by LeaVerou** [comment]
Hm, I suppose we could add Babel for the generated bundles and use a NodeJS 12 target.
