### ISSUE TITLE
OKLCH support without `%`

### ISSUE THREAD

**Issue by ai** [LeaVerou/color.js#207]
Is it incorrect value?

```
:root {
    --border-p3: oklch(0% 0 0);
}
```

I thought that `0 == 0%`.

**Comment by svgeesus** [comment]
Could you clarify what you are asking, exactly?

If you are asking "is this correct syntax [per CSS Color 4]()" then yes.

```
    oklab() = oklab( [ <percentage> | <number> | none]
    [ <percentage> | <number> | none]
    [ <percentage> | <number> | none]
    [ / [<alpha-value> | none] ]? )
```

If you are asking whether browsers accept this syntax, then the answer is that it depends on how recently they were updated to take into account this relatively recent addition of percentage reference ranges. I [made an exhaustive test for this for `color()`](https://wpt.fyi/results/css/css-color/parsing?label=experimental&label=master&aligned) and need to make a similar test for `oklab()` and friends.

**Comment by LeaVerou** [comment]
> I thought that `0 == 0%`.

Nope. [Only for lengths](https://drafts.csswg.org/css-values/#length-value) you can use `0` without a unit and it's the same. Generally `0%` is not the same as `0`, and for a parameter to accept both, it needs to accept `<number-percentage>`. E.g. try `hsl(0 0 0)` in browsers, you'll see it doesn't work.
