### ISSUE TITLE
oklab() and oklch() do not accept plain numbers for lightness

### ISSUE THREAD

**Issue by LeaVerou** [LeaVerou/color.js#225]
Lines to be changed:

https://github.com/LeaVerou/color.js/blob/main/src/spaces/oklab.js#L71
https://github.com/LeaVerou/color.js/blob/main/src/spaces/oklch.js#L65

Lab and LCH are fine:

https://github.com/LeaVerou/color.js/blob/main/src/spaces/lab.js#L71
https://github.com/LeaVerou/color.js/blob/main/src/spaces/lch.js#L64

**Comment by svgeesus** [comment]
Lab and LCH also need to be changed, as [serialization of CIE Lightness is now to `<number>`](https://w3c.github.io/csswg-drafts/css-color-4/#serializing-lab-lch) as is [serialization of OK Lightness](https://w3c.github.io/csswg-drafts/css-color-4/#serializing-oklab-oklch)
