### ISSUE TITLE
All color functions should also accept percentages

### ISSUE THREAD

**Issue by LeaVerou** [LeaVerou/color.js#226]
Per the recent change in Color 4, all color functions should now accept percentages, and resolve them based on the reference ranges.

This is a fairly simple change. E.g. for Lab, you'd change [this line](https://github.com/LeaVerou/color.js/blob/main/src/spaces/lab.js#L71):

```js
			coords: ["<percentage> | <number>", "<number>", "<number>"],
```

to: 
```js
			coords: ["<percentage> | <number>", "<number> | <percentage>", "<number> | <percentage>"],
```

(Note that percentage needs to come second, otherwise it would affect serialization)

**Comment by svgeesus** [comment]
That doesn't seem to be sufficient to resolve the percentages. Where do the reference ranges go?

> [Lab for a and b](https://w3c.github.io/csswg-drafts/css-color-4/#specifying-lab-lch): -100% = -125, 100% = 125 

> [Oklab for a and b](https://w3c.github.io/csswg-drafts/css-color-4/#specifying-oklab-oklch): -100% = -0.4, 100% = 0.4

**Comment by LeaVerou** [comment]
> That doesn't seem to be sufficient to resolve the percentages. Where do the reference ranges go?
> 
> > [Lab for a and b](https://w3c.github.io/csswg-drafts/css-color-4/#specifying-lab-lch): -100% = -125, 100% = 125
> 
> > [Oklab for a and b](https://w3c.github.io/csswg-drafts/css-color-4/#specifying-oklab-oklch): -100% = -0.4, 100% = 0.4

Good point. [There is a way to specify a range](https://github.com/LeaVerou/color.js/blob/main/src/spaces/srgb.js#L5), but I think that would constrain the number

**Comment by svgeesus** [comment]
Fixed by https://github.com/LeaVerou/color.js/pull/314
