### ISSUE TITLE
Legacy builds are not included in NPM package.

### ISSUE THREAD

**Issue by jgerigmeyer** [LeaVerou/color.js#232]
New legacy builds were added in #215 to support older versions of Node etc, but it appears that the legacy built files are missing in the published NPM package for v0.4.1: https://unpkg.com/browse/colorjs.io@0.4.1/dist/

I'm not sure what the build/release process is for colorjs.io, but when I `npm pack` locally the files are included correctly -- perhaps `npm run build` wasn't run before the new release? In case that's the issue, I'll open a PR to address that with a `prepack` script.

**Comment by LeaVerou** [comment]
Ugh, I'm an idiot. 🤦🏽‍♀️ Yes, I released without running `npm run build` 🤦🏽‍♀️🤦🏽‍♀️🤦🏽‍♀️

**Comment by LeaVerou** [comment]
(Not closed until I release a patch version lol)

**Comment by LeaVerou** [comment]
@jgerigmeyer Are you aware of any convention for what that version number would be?

**Comment by jgerigmeyer** [comment]
> @jgerigmeyer Are you aware of any convention for what that version number would be? We currently use the "patch" version number for releases with actual features, since we're still in 0.x.y, so it would need to be a `-something`

@LeaVerou Oh, that's a great question! I don't feel strongly, but my general approach is that during pre-1.0 I treat "patch" and "feature" the same, so I would lean toward `v0.4.2` rather than `v0.4.1-patch.1`. (This is I think the main approach outlined in https://github.com/semver/semver/issues/333, for example.) Partially because I find it confusing when the "current" release is a `0.x.y-something`... but really I'm fine with whatever you prefer!

**Comment by LeaVerou** [comment]
> One downside of using `v0.4.1-patch.1` is that it's not installed by either `^0.4.1` or even `^0.4.1-patch.1`, and can only be installed with `0.4.1-patch.1` directly. But that's probably best practice for a pre-1.0 dependency anyway, so 🤷

Ah, I didn't know that. Even more reason to [implement alpha blending](https://github.com/LeaVerou/color.js/issues/230 ) and release it in 0.4.2!
