### ISSUE TITLE
Fix link from https://lea.verou.me/2012/10/easy-color-contrast-ratios/ ?

### ISSUE THREAD

**Issue by alanhogan** [LeaVerou/color.js#243]
I noticed that on https://lea.verou.me/2012/10/easy-color-contrast-ratios/ there is still a broken link to http://leaverou.github.com/contrast-ratio/ (this results in 404). I think it should now point here to color.js, no? 

Love this tool, wow!

**Comment by alanhogan** [comment]
Note: The broken link is "my own tool" (the pull requests link was already updated to point to https://github.com/LeaVerou/contrast-ratio)

**Comment by LeaVerou** [comment]
Fixed, thanks!

Please note contrast-ratio doesn't use color.js yet (needs https://github.com/LeaVerou/color.js/issues/230 to be fixed first)
