### ISSUE TITLE
toString({ format: "hex" }) Only Works for sRGB

### ISSUE THREAD

**Issue by AntonPalmqvist** [LeaVerou/color.js#245]
Hi!

I'm trying to get the hex value of a **sRGB-linear** color, but it doesn't seem to work. It only works for a color in the regular sRGB color space. I expected this to work for any RGB color space.

This is what I'm trying:

```
let color = new Color("sRGB-linear", [0.944, 0.776, 0.373]);
console.log(color.space.name + " " + color.toString({ format: "hex" }));
```
and the output I get is: **color(srgb-linear 0.944 0.776 0.373)**

Whereas:

```
let color = new Color("sRGB", [0.944, 0.776, 0.373]);
console.log(color.toString({ format: "hex" }));
```
gives me the expected output: **#f1c65f**

Since a hexadecimal value is just a different, base16, representation of RGB values, shouldn't it work with any RGB color?
I've seen software that accepts hex color codes in both sRGB-linear and sRGB (Unreal Engine does this for example).
Hex color codes doesn't necessarily have to be sRGB-only from what I know.

Best regards,
Anton

**Comment by LeaVerou** [comment]
While in some places hex has indeed been used as just another representation of any RGB space, Color.js is based on the CSS Color specifications, in which hex colors **only** refer to sRGB. Note that in wider color spaces, hex is a poor representation, as you usually need more than 8 bits per channel, and hex is tied to 8 bits. It might have been reasonable for linear sRGB, but then parsing a hex color would be ambiguous: do you parse it as sRGB or sRGB linear?

However, here is a workaround to do what you want:

```js
let color_srgb = new Color("sRGB", color_linear.coords, color_linear.alpha);
console.log(color_srgb.toString({format: "hex"});
```
