### ISSUE TITLE
There's two type definitions of Color instance

### ISSUE THREAD

**Issue by latin-1** [LeaVerou/color.js#258]
```ts
import Color from "colorjs.io";

const color1 = new Color("black"); // Color from "colorjs.io/types/src/index.d.ts"
const color2 = color1.to("srgb"); // Color "from colorjs.io/types/src/color.d.ts"

// @ts-expect-error Type 'Color' is missing the following properties from type 'Color': uv, xy, contrast, contrastWCAG21, and 18 more.
const color3: Color = color2;
```

**Comment by MysteryBlokHed** [comment]
That's because there are two different versions of the `Color` object:

<https://github.com/LeaVerou/color.js/blob/main/src/color.js>
<https://github.com/LeaVerou/color.js/blob/main/src/index.js>

**Comment by MysteryBlokHed** [comment]
Actually, I've looked at the code again and I can see what the problem is. I'm working on a PR that I think will fix it.
