### ISSUE TITLE
keywords.js Editing Issue

### ISSUE THREAD

**Issue by P-Star7** [LeaVerou/color.js#263]
I made a local change to my copy of src/keywords.js for the Closed Named Color app to provide my own color list. Running it gives me the same blank screen as in issue #262 , but using the original version of keywords.js makes the app work perfectly well as it does on the externally-hosted demo.
The original copy of keywords.js is in this repository in the src folder.
Here is my personalized copy in a .zip file.
[keywords.zip](https://github.com/LeaVerou/color.js/files/10301435/keywords.zip)
This color notation looks correct and exactly like the original, doesn't it? Did I overlook something?

Edit: Okay, I accidentally left a comma after the last table entry, but removing it fixed nothing.

**Comment by LeaVerou** [comment]
Hi there @P-Star7,

We don't usually download zip files and extract them to reply to issues. Could you please include a sample of the change you made? Or post it in a gist and link to it? 

Are you getting any errors in the console? I've asked you in the other issue as well, and got no response. Do you know how to open the browser developer tools? I can help if not, but don't want to go into that if you already know. 

Cheers

**Comment by P-Star7** [comment]
> Hi there @P-Star7,
> 
> We don't usually download zip files and extract them to reply to issues. Could you please include a sample of the change you made? Or post it in a gist and link to it?
> 
> Are you getting any errors in the console? I've asked you in the other issue as well, and got no response. This is the first thing you do when something is not working, open the console and see what's there. Do you know how to open the browser developer tools? I can help if not, but don't want to go into that if you already know.
> 
> Cheers

Ah thanks for telling me about gists. And also thanks for telling me about the console. I knew about it but had overlooked the "issues" tab, and it told me which line had an error. I had forgotten to enclose one of the colour names in brackets. Here we go. Sorry for all the stupid questions, and thanks for making such a great tool in the first place.
![image](https://user-images.githubusercontent.com/26371167/209571547-5c1365dd-42e3-4395-b09e-e4cec85e5963.png)
