### ISSUE TITLE
Use NaN for undefined coords

### ISSUE THREAD

**Issue by LeaVerou** [LeaVerou/color.js#27]
This will resolve #14 and #23.

If polar space colors are created, we should preserve their coordinates, but if we are converting to them, we should use NaN for coords that are undefined (let's start from hue for achromatic colors, not sure if this is needed for chroma/saturation).

This does mean that roundtripping an achromatic color would lose its hue data, but I don't think that's a significant problem.

Tasks needed:

- [x] 1. Handle NaN values in interpolation (interpolating with NaN returns the other coord)
- [x] 2. Output NaN for hue when converting achromatic colors to any color space with hue
- [x] 3. Output NaN as 0 in `toString()` since it needs to produce a valid color
- [x] 4. Handle NaN in deltaE (same as interpolation I guess)
- [x] 5. Handle NaN in color contrast 
- [x] 6. Handle NaN in color conversions
- [ ] 9. Handle NaN anywhere else

**Comment by svgeesus** [comment]
> CMC uses LCH and will need to take this into account

CMC is already [correct](https://github.com/LeaVerou/color.js/blob/13135c9d01a7113de2ba6c922b4f9f79450c6005/src/deltaE/deltaECMC.js#L90-L91)

**Comment by svgeesus** [comment]
> Handle NaN in color contrast

Contrast [only uses luminance](https://github.com/LeaVerou/color.js/blob/13135c9d01a7113de2ba6c922b4f9f79450c6005/src/color.js#L210-L221) so should not be affected by `NaN` in hue.
