### ISSUE TITLE
The netlify button in the readme

### ISSUE THREAD

**Issue by rohinish404** [LeaVerou/color.js#273]
The netlify (success) button in the readme is opening a page where the deploys of colorjs are being displayed. Shouldn't there be a button to link to official website instead of linking to this page(netlify deploys one).
<img width="1429" alt="Screenshot 2023-01-21 at 2 18 16 PM" src="https://user-images.githubusercontent.com/92542124/213859519-65de220f-8bf9-4afc-bfc5-b0de9f44d581.png">

**Comment by LeaVerou** [comment]
I’m not sure I fully understand the issue. There’s a link to the official website right under?

<img width="757" alt="image" src="https://user-images.githubusercontent.com/175836/213870438-d54b7dc6-09e4-4c39-9fae-de3bdd21b53b.png">

**Comment by rohinish404** [comment]
I wanted to ask why is there a button to the netlify deploys page of colorjs?

**Comment by LeaVerou** [comment]
Why not? 😁

**Comment by rohinish404** [comment]
I don't have any reply to that..it's just i haven't seen deploy link in any of the projects(whichever i have came across) so i thought maybe that button can be replaced by the button linking to actual website 🙂
Shall i close the issue?

**Comment by LeaVerou** [comment]
I believe that's just the stock Netlify button, which I've definitely seen in other projects (though never clicked to it). I personally don't see anything wrong with linking to the deploys, and there's another link to the website.

**Comment by rohinish404** [comment]
Okay..no problem🙂
