### ISSUE TITLE
Refine rec2100-pq support for Chrome Canary (rec2020 Experimental Feature in ver108+)

### ISSUE THREAD

**Issue by mdrejhon** [LeaVerou/color.js#274]
Hello,

My current version of color.js I'm trialling doesn't seem to support rec2100-pq, and there is no instructions for: https://colorjs.io/docs/output.html

I am developing a HDR version of TestUFO (www.testufo.com) and some of the display motion-blur-performance tests require a color picker, such as www.testufo.com/chase amongst 30 other selectable tests at upper-right corner;

I am making it compatible with Safari "display-p3" and Chrome "rec2100-pq" (Canary support).  

It kinda works but I need a color picker polyfill.

What's the ETA for rec2100 (rec2020 colorspace) support (via "rec2100-pq"), or is this already slipstreamed into the dev version (I couldn't tell, from searching around)?   

I'm already blitting rec2020 .avif's to rec2100-pq &lt;CANVAS&gt; 

Sincerely
Founder of Blur Busters / TestUFO
(World's most popular site for testing "Better Than 60Hz" displays)

**Comment by mdrejhon** [comment]
For those unaware of how I'm creating rec2020 canvas in Chrome Canary, I have to go to chrome://flags and enable "Experimental Features"

Then I do this:

```
 // Create HDR canvas (rec2100-pq, Canary 108 or later)
[...]
this.surface = this.canvas.getContext("2d", {colorSpace:'rec2100-pq', pixelFormat:'float16'});
this.canvas.drawingBufferColorSpace = 'rec2100-pq';
this.canvas.unpackColorSpace = 'rec2100-pq';
[...]
```

Works beautifully, and HDR AVIF sprites work fine in rec2020 colorspace.  

Now I'm missing a rec2020-compatible color picker.   

Help?

**Comment by Crissov** [comment]
No helpful answer here, just someone wondering what’s the deal with the `-pq` suffix?

https://w3c.github.io/csswg-drafts/css-color-4/#predefined-rec2020

**Comment by facelessuser** [comment]
@Crissov It's not just the suffix, the entire name is different from Rec. 2020. Notice the number is different (rec2100). This is an HDR color space that transforms the SDR Rec 2020 color space. There are two such color spaces defined under Rec. 2100: https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.2100-2-201807-I!!PDF-E.pdf.

The spec defines two HDR color spaces, one that uses "Perceptual Quantization" (PQ) and the other that uses "Hybrid Log Gamma" (HLG). Because of this, the prefixes are needed to distinguish which Rec. 2100 color space you are talking about. Check out the documentation to learn more.

**Comment by mdrejhon** [comment]
> No helpful answer here, just someone wondering what’s the deal with the `-pq` suffix?

Theres "rec2100-pq" and "rec2100-hlg".  TestUFO HDR is currently going for "rec2100-pq".

**Comment by facelessuser** [comment]
It seems just doing this in CodePen works. I'm not sure if all packaged releases register it by default, and if not, I'm not sure how to register unregistered plugins as the documentation doesn't explain it well.

```js
import Color from "https://colorjs.io/dist/color.js";
console.log(new Color('red').to('rec2100pq'));
```

One thing to note is that the ID uses no hypen before `pq`, but the CSS ID used for CSS strings does. It's a bit confusing.

**Comment by mdrejhon** [comment]
Excellent catch on this hyphen-free inconsistency!   This tripped me up trying to figure out if this beastly github package could support rec2100 or not.

Let me give that a try.   

Documentation will need to be improved due to Chrome Canary's support for rec2100-pq with the hyphen....

**Comment by facelessuser** [comment]
Yeah, in case it wasn't clear to anyone, color.js does support the name`rec2100-pq` with a hyphen, but only for CSS input/output. The color space ID uses no hyphens. I know this has tripped me up a number of times using color.js.

```js
> const { default: Color } = require("colorjs.io");
undefined
> let color = new Color('red').to('rec2100pq')
undefined
> color.toString()
'color(rec2100-pq 0.5325 0.327 0.2201)'
> let color2 = new Color(color.toString())
undefined
> color2.toString()
'color(rec2100-pq 0.5325 0.327 0.2201)'
```

I know this has tripped me up multiple times This exists with other spaces as well, like Display P3. You just have to remember that the ID may not always match the CSS ID.

```js
> new Color('display-p3', [1, 0, 0])
Uncaught TypeError: No color space found with id = "display-p3"
    at Function.get (/Users/facelessuser/Code/github/color.js/dist/color.cjs:610:11)
    at new Color (/Users/facelessuser/Code/github/color.js/dist/color.cjs:3991:28)
> new Color('p3', [1, 0, 0]).toString()
'color(display-p3 1 0 0)'
```

**Comment by mdrejhon** [comment]
Thanks.

**Comment by mdrejhon** [comment]
I think I am now able to use color.js as part of TestUFO HDR.  Keep tuned.

I might run into other blockers, but I think I went past the major one.

**Comment by svgeesus** [comment]
The name [`rec2100-pq`](https://drafts.csswg.org/css-color-hdr/#valdef-color-rec2100-pq) is from the CSS Color HDR unofficial draft, and is also used in the [HDR Canvas proposal](https://github.com/w3c/ColorWeb-CG/blob/main/hdr_html_canvas_element.md#add-color-spaces-intended-for-use-with-hdr-images)

**Comment by svgeesus** [comment]
Closing the loop, color.js has had [rec2100-pq](https://github.com/LeaVerou/color.js/blob/main/src/spaces/rec2100-pq.js) and [rec2100-hlg](https://github.com/LeaVerou/color.js/blob/main/src/spaces/rec2100-hlg.js) for a while now. They are listed in [Supported Color Spaces](https://colorjs.io/docs/spaces.html)
