### ISSUE TITLE
CSS variables are not working

### ISSUE THREAD

**Issue by neznayer** [LeaVerou/color.js#275]
Throws error when I try to access css color variable

```js
import Color from "colorjs.io";

// This works: 
const someColorString = getComputedStyle(document.documentElement).getPropertyValue('--some-color')

//This don't: 
const someColor = new Color("--some-color") 
// throws error here: Uncaught TypeError: Could not parse --some-color as a color. Missing a plugin?


```
StackBlitz: 
https://stackblitz.com/edit/vitejs-vite-5fziex?file=main.js

"Missing plugin?" part intrigues me, but I can't find any plugins for it... so in some sense, I do missing a plugin 😅

**Comment by LeaVerou** [comment]
Where did you see this syntax? We removed it in #160

**Comment by neznayer** [comment]
@LeaVerou 
> Where did you see this syntax? We removed it in #160

Oh, I see.  Could you please tell me what the latest version of the library which do support that syntax? 

I saw that syntax in the code of our project which I currently jumping-in. 
Apparently, my coworker was using some "Color.js" file directly, with contents is a minified `colorjs.io` of some version, I believe.
 I switched to using the npm package, but now it don't working, because `new Color("-some-color")` is uses everywhere throuhout the project..

**Comment by neznayer** [comment]
> Oh, I see. Could you please tell me what the latest version of the library which do support that syntax?

Nevermind, just found that it's  apparently v.0.0.7.
Thank you! 🙇‍♂️

**Comment by LeaVerou** [comment]
@neznayer Aw, it's a shame to be using such an old version.

`new Color("--foo")` is literally a shortcut to `new Color(getComputedStyle(document.documentElement).getPropertyValue("--foo"))`. You could probably write a helper and replace it en masse.
