### ISSUE TITLE
Publish new release?

### ISSUE THREAD

**Issue by eamodio** [LeaVerou/color.js#276]
Hi all -- I'm trying to incorporate colorjs in my TypeScript project and have run into a few issues with the typings, which have already been fixed but haven't been released yet. Is there any chance to get a new release out (soon) with all those updated typings?

Thanks!

**Comment by LeaVerou** [comment]
Sure, I'll try to get one out by Friday!

**Comment by eamodio** [comment]
Thank you so much!

**Comment by LeaVerou** [comment]
Done!

https://github.com/LeaVerou/color.js/releases/tag/v0.4.3
https://www.npmjs.com/package/colorjs.io
