### ISSUE TITLE
"deltaE76 is not defined"

### ISSUE THREAD

**Issue by drewlarsen** [LeaVerou/color.js#282]
Starting with an essentially empty html file:

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>colorio test</title>
    <script src="https://colorjs.io/dist/color.global.js"></script>
</head>
<body>
</body>
</html>
```

and following the instruction from the readme:

> Or, if you'd rather just have Color as a global variable, the classic way, just include the following script in your HTML:
> <script src="https://colorjs.io/dist/color.global.js"></script>

I get the following error in the browser console:

```
index.js:9 Uncaught ReferenceError: deltaE76 is not defined
    at index.js:9:2
    at index.js:32:30
```

<img width="450" alt="image" src="https://user-images.githubusercontent.com/2637780/217401963-1fc4a13d-4e56-4174-848c-82e800d7cc0f.png">

**Comment by MeltonEngServ** [comment]
I was using the library through a CDN as well, and It was working well, but now I get the same error.

**Comment by isohelio** [comment]
Same here.

Is there any way to refer to the previous version, while waiting for a fix?

**Comment by isohelio** [comment]
It's breaking the colorjs demos, if you want to see an example.

https://colorjs.io/apps/picker/

**Comment by qgustavor** [comment]
Would not be better if colorjs.io handled versioning and the documentation recommended locking versions? For the while I'll be using https://unpkg.com/colorjs.io@0.4.2/dist/color.js instead of https://colorjs.io/dist/color.js.

**Comment by svgeesus** [comment]
Closed by https://github.com/LeaVerou/color.js/pull/283
