### ISSUE TITLE
Add descriptions to the Color object

### ISSUE THREAD

**Issue by AntonPalmqvist** [LeaVerou/color.js#286]
Hi!

It would be nice to have color space descriptions from the documentation accessible in the Color object. However I understand they might make this library heavy, so please feel free to close this issue if this would just add bloat.

Best, 
Anton

![image](https://user-images.githubusercontent.com/13031779/219970065-df6c3db8-2361-4b87-8381-06033deca836.png)

**Comment by LeaVerou** [comment]
Hi there,

What's the use case? The data is already machine readable, and CORS-enabled, you can just `fetch("https://colorjs.io/get/modules.json")`. Does this help?

**Comment by AntonPalmqvist** [comment]
Didn't know I could do that. That definitely helps, thank you!
