### ISSUE TITLE
[color notebook] Live playground for sharing snippets

### ISSUE THREAD

**Issue by LeaVerou** [LeaVerou/color.js#29]
Snippets can be saved as gists or in Github repos, as Markdown.
This way, people can share entire Color notebook documents if they so desire.

Can be implemented with Mavo and a little bit of custom JS for saving a new Gist.

**Comment by LeaVerou** [comment]
This has been done literally years ago lol

**Comment by eeeps** [comment]
@LeaVerou
Saving is broken for me, right now. Not sure if it's broken for others as well?

What I really want though is a URL to share for a notebook + its code. Snooping around with view source, I've gotten as far as: https://colorjs.io/notebook/?storage=https://gist.githubusercontent.com/eeeps/26b83123a4b5b6012bda29d4f2e9ee7f/raw/07f808a9471bb0e1d4ea0f0765ba1b3a611216ee/super-duper-extra-teal.js

The code appears! But it's not styled, evaluated, or editable.

<img width="1097" alt="Screenshot 2023-11-29 at 12 03 38" src="https://github.com/color-js/color.js/assets/3441390/53dc9524-50f9-4ae9-9236-3e3717238639">
