### ISSUE TITLE
Error when passing a Color object to the procedural api

### ISSUE THREAD

**Issue by lloydk** [LeaVerou/color.js#303]
Not sure if this is a bug or working as intended but it looks like the object oriented and procedural APIs are not compatible with each other. Passing a `Color` object to the `to` function results in the following exception:

```sh
~/work/test$ node index.js
file:///home/lloydk/work/test/node_modules/colorjs.io/src/space.js:316
                throw new TypeError(`${space} is not a valid color space`);
                      ^

TypeError: sRGB (srgb) is not a valid color space
    at ColorSpace.get (file:///home/lloydk/work/test/node_modules/colorjs.io/src/space.js:316:9)
    at getColor (file:///home/lloydk/work/test/node_modules/colorjs.io/src/getColor.js:24:28)
    at to (file:///home/lloydk/work/test/node_modules/colorjs.io/src/to.js:13:10)
    at file:///home/lloydk/work/test/index.js:8:1
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
```
Code to reproduce:

**package.json**
```json
{
  "name": "test",
  "main": "index.js",
  "type": "module",
  "dependencies": {
    "colorjs.io": "^0.4.3"
  }
}
```

**index.js**
```js
import Color from 'colorjs.io'
import { ColorSpace, sRGB, OKLCH, to } from 'colorjs.io/fn'

ColorSpace.register(OKLCH)
ColorSpace.register(sRGB)

let bg = new Color('white')
to(bg, 'oklch')
```

I think the issue is that there are two `ColorSpace` classes being loaded in the above code. One from `./dist/color.js` and the other from `./src/index-fn.js`. Because the classes are different the `instanceof` check [here](https://github.com/LeaVerou/color.js/blob/4a13fd3e970b59ca6d7776a586eaeac5a1b10faa/src/space.js#L295) fails and eventually the code hits the end of the method and throws an exception.

Why would you want to mix the object oriented API with the procedural API? In my case I was writing some tests for code that used the procedural API and I thought it would be more convenient to use the `Color` class.

**Comment by LeaVerou** [comment]
In general we do want to allow mixing them whenever possible. 

To help track this down, could you check if you can reproduce it without a bundler, e.g. in CodePen?

> I think the issue is that there are two `ColorSpace` classes being loaded in the above code. One from `./dist/color.js` and the other from `./src/index-fn.js`. Because the classes are different the `instanceof` check [here](https://github.com/LeaVerou/color.js/blob/4a13fd3e970b59ca6d7776a586eaeac5a1b10faa/src/space.js#L295) fails and eventually the code hits the end of the method and throws an exception.

Yes, that sounds about right. Mixing the procedural and OO versions of the API should be ok, but mixing two different isntances of Color.js, not sure how we could support that :/

**Comment by lloydk** [comment]
Here is a [codepen](https://codepen.io/lloydk/pen/JjmJJer) that demonstrates the issue. The exception doesn't show up for me in the codepen console but you can see it in the developer tools console.

This will fail with the same exception mentioned above.
```js
import Color from "https://colorjs.io/dist/color.js"
import { ColorSpace, sRGB, OKLCH, to } from "https://colorjs.io/src/index-fn.js";

ColorSpace.register(OKLCH)
ColorSpace.register(sRGB)

let bg = new Color('white')
let oklch = to(bg, 'oklch')

console.log(oklch) 

```

Importing everything from src works.
```js
import Color from "https://colorjs.io/src/index.js";
import { ColorSpace, sRGB, OKLCH, to } from "https://colorjs.io/src/index-fn.js";

ColorSpace.register(OKLCH)
ColorSpace.register(sRGB)

let bg = new Color('white')
let oklch = to(bg, 'oklch')

console.log(oklch) 

```

**Comment by LeaVerou** [comment]
> Importing everything from src works.

I wouldn't consider it a bug then. 🤷🏽‍♀️ It's not that you can't mix the procedural and OO APIs (you can), but of course if you import parts of a library from one place and other parts from another place it will not work. I can't even think of how it could, but I'd be happy to review PRs if someone has ideas about how to enable this with a reasonable amount of code.

Btw, you can access the `ColorSpace` object used by a `Color` class via `Color.Space` but even doing `Color.Space = ColorSpace` before anything else runs doesn't seem to work, I guess because `to()` still imports the other `ColorSpace` object.

**Comment by lloydk** [comment]
The codepen example only works because it's bypassing `package.json` and accessing the `src` directly.

One possible fix which works for my small test case is to change this line in the exports section of `package.json` from:

```json
"import": "./dist/color.js",
```
to

```json
"import": "./src/index.js",
```

I'm not a javascript guru so I can't really say if that change will break anything.

The other option is to add another export to `package.json`. This also works for my small test case:

```json
"./color": {
	"types": "./types/index.d.ts",
	"import": "./src/index.js"
},
```

Then you could `import Color from "colorjs.io/color";`

**Comment by LeaVerou** [comment]
I would be fine with changing the main import to point to use src. @jgerigmeyer can you think of any reason not to?

**Comment by jgerigmeyer** [comment]
Hm, this is an interesting question. 🤔 It's certainly an edge case, but I don't see any harm in switching the default `import` endpoint to `./src/index.js`. At that point we're essentially no longer using the rollup bundle for ESM, but I guess that's okay? I mean, it doesn't really add anything as far as I can tell. And we're still exposing the `dist/color.js` bundle for anyone who wants it. 👍

**Comment by sidewayss** [comment]
> I would be fine with changing the main import to use src. @jgerigmeyer can you think of any reason not to?

It's as you stated above:

> Btw, you can access the ColorSpace object used by a Color class via Color.Space but even doing Color.Space = ColorSpace before anything else runs doesn't seem to work, I guess because to() still imports the other ColorSpace object.

If you import `Color` from `src`, the `Color.spaces = ColorSpace.registry` is empty, for example.  Importing from `dist` seems to fully populate everything.  @jgerigmeyer 's previous comment might address this with:

> At that point we're essentially no longer using the rollup bundle for ESM, but I guess that's okay?

But I don't know what that means, and I wanted to make sure. I'm currently importing directly from `dist`, so this doesn't bother me personally.

**Comment by sidewayss** [comment]
IMO the core issue is:  Is all the functionality available via the chosen import source?

Now that `Color` has `Color.Space` and `Color.spaces`, I can import from `dist` and get everything I need so far.  I am getting spaces via the registry, for example, instead of importing the files from `src`.

Are some things only available via `src`?  Should they be made available via `dist`, where everything is populated?
For users that import from `src`, what do they need to know about populating whatever they need, like the registry?
