### ISSUE TITLE
`Color.steps` regression

### ISSUE THREAD

**Issue by argyleink** [LeaVerou/color.js#309]
"Cannot read properties of undefined (reading 'id')"
Error is related to colorspace IDs `xyz` and `srgb-linear`
https://codepen.io/argyleink/pen/JjZajmb

Was able to patch demos like this one https://observablehq.com/@argyleink/hue-interpolation by removing the `srgb` outputSpace option AND/OR removing `xyz` and `srgb-linear` from the `space` option.

**Comment by LeaVerou** [comment]
Hi Adam! Sorry about the regression! I cannot see any error in the codepen you linked to, but I just pushed a speculative fix, could you please check if that fixes things?
