### ISSUE TITLE
Support grad, rad, and turn angle units for the hue value of hsl()

### ISSUE THREAD

**Issue by straker** [LeaVerou/color.js#311]
I'd like to be able to pass any of the 4 hue angle units (`deg`, `grad`, `rad`, and `turn`) to the `new Color(str)` constructor, but at the moment only `deg` works.

```js
new Color('hsl(90deg 40% 50%)') // works
new Color('hsl(100grad 40% 50%)') // throws
new Color('hsl(1.57rad 40% 50%)')  // throws
new Color('hsl(0.25turn 40% 50%)') // throws
```

**Comment by Crissov** [comment]
See issue #180 and PR #181. I kinda lost interest back then.

**Comment by LeaVerou** [comment]
We're happy to merge a PR to support other angle units.
