### ISSUE TITLE
Unexpected WCAG21 contrast of 297

### ISSUE THREAD

**Issue by lukasoppermann** [LeaVerou/color.js#313]
Hey, this is a really great package.

Sadly I am running into an issue measuring the contrast between two colors in `oklch` format. I am probably doing something wrong, but I can't figure out what.

I created a small wrapper to clean up my code, see below.

What I am doing here is taking two `oklch` colors in an `array` format. Using them to create a color object using the `new Color` constructor and creating a contrast using `color1.contrast(color2, "WCAG21")`. 

I am than using `Math.floor` to round the result to two decimal points. (Removing this step does not change the contrast, it is still 297 just with more decimal points).

```js
export const getColorContrast = (oklchArray1: oklch, oklchArray2: oklch) => {
  const color1 = new Color("oklch", oklchArray1);
  const color2 = new Color("oklch", oklchArray2);
  return Math.floor(color1.contrast(color2, "WCAG21") * 100) / 100;
}
```

The result seems somewhat correct for lower contrasts but gets further off the higher the contrast.

This code for example produces a result in `contrast` of `37.03697030190807`:

```js
  let color1 = new Color("oklch", [30, 0, 0.1]);
  let color2 = new Color("oklch", [100, 0, 0]);
  let contrast = color1.contrast(color2, "WCAG21");
```

Please let me know if I can provide any additional helpful information.

**Comment by facelessuser** [comment]
I can't tell exactly what you mean by "the results are off" as you aren't providing what your results are being compared against to determine that they are off.

What I can say is that it seems like you are using the wrong scaling for OkLCh lightness in your last example. You are using `30` and `100` for the lightness, but OkLCh lightness is supposed to be between `0` and `1`.  So, maybe you meant to use `0.3` and `1, and that is the cause of your confusion?

**Comment by lukasoppermann** [comment]
🤦‍♂️ Yes, this was the problem, thanks. I somehow had the format from mdn in mind: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/oklch

This solved, it, great.
