### ISSUE TITLE
Lab spaces (lab, lab-d65, and oklab) should accept `Lightness` in addition to `L` for first coordinate name.

### ISSUE THREAD

**Issue by jgerigmeyer** [LeaVerou/color.js#345]
Most spaces accept full spelled out versions of coordinate names as the `coordId`, but the three Lab spaces only accept `L` and not `Lightness`.

```js
const color = new Color("red");
console.log(color.lch.lightness); // 54.3
console.log(color.lab.l); // 54.3
console.log(color.lab.lightness); // throws error
```

@LeaVerou Was this an intentional design decision? I can't find anything in the spec that would warrant this. If it wasn't intentional, I'm happy to submit a PR.

**Comment by LeaVerou** [comment]
Hm. We did intentionally go with L for Lab, but now I'm not sure it was a good idea. @svgeesus, thoughts?

**Comment by svgeesus** [comment]
If we allow it in the other spaces then we should here, too.
