### ISSUE TITLE
Color converted to Oklab has too much chroma

### ISSUE THREAD

**Issue by eeeps** [LeaVerou/color.js#355]
```
let color = new Color("dodgerblue");
color.to("oklab") // oklab(65.2% -0.1 -0.2)
```

[The resulting color is different than `dodgerblue`](https://codepen.io/eeeps/pen/rNPdBxM), or `dodgerblue` converted to any other space, even OKLCH.

**Comment by facelessuser** [comment]
@eeeps You need to use a higher precision. If you are using the "playground" in the documentation, it is currently forcing a precision of 3 when representing the color object in the preview. Output to string which will use the default of 5 for precision. This will give you sufficient precision.

```js
> new Color('dodgerblue').to('oklab').toString()
'oklab(65.201% -0.055 -0.182)'
```

**Comment by eeeps** [comment]
Huh! [Confirmed!](https://codepen.io/eeeps/pen/dyambgg) Thank you!
