### ISSUE TITLE
Gamut fitting algorithm when lch chroma is negative seems off

### ISSUE THREAD

**Issue by facelessuser** [LeaVerou/color.js#52]
So, let me start off by mentioning that I realize chorma of < 0 is not really a normal use case and I was more experimenting with corner cases in the algorithm. My interest was that I was implementing the Lch Chroma gamut fitting that you guys describe, and I was comparing against your output as a sanity check.

What I noticed is this:

<img width="994" alt="Screen Shot 2020-09-16 at 9 41 31 AM" src="https://user-images.githubusercontent.com/1055125/93361096-af6c7d80-f801-11ea-8de4-ed1ea507d79a.png">

What this shows is that when we fit an Lch value which has a negative chroma, the color doesn't quite come out as expected. But if we convert the Lch color to Lab and back to Lch, then we can fit it and get a more expected result.

Now, I implemented the deltaE2000 directly from http://www2.ece.rochester.edu/~gsharma/ciede2000/ciede2000noteCRNA.pdf, so I was very literal in my translation to code. With that said, I noticed one difference from what I'm doing than from what you guys are doing. That is specifically getting the initial chroma values by calculating it from `a` and `b`.

```py
    lab1 = color.convert("lab")
    lab2 = color2.convert("lab")

    l1, a1, b1 = lab1._channels
    c1 = math.sqrt(math.pow(a1, 2) + math.pow(b1, 2))
    l2, a2, b2 = lab2._channels
    c2 = math.sqrt(math.pow(a2, 2) + math.pow(b2, 2))
```

You guys seem to just take the chroma from the already calculated Lch value, which I am assuming is coming out as negative. I suspect this may be the issue unless there is some kind of handling that occurs before we get here. I tried to change to what you guys were doing only to run into failures, so I imagine there may be something else occurring before you get here. Since my library isn't carrying around all the color spaces already, I have to explicitly convert to a color space, so I imagine that
may also have forced me not to run into this issue.

```js
	let [L1, a1, b1] = color.lab;
	let C1 = color.chroma;
	let [L2, a2, b2] = sample.lab;
	let C2 = sample.chroma;
```

I am seeing consistent behavior by calculating the chorma from `a` and `b`:

```py
>>> c = colorcss("lch(100% -50 10)")
>>> c.fit_gamut("srgb")
>>> c.to_string()
'lch(97.977% 9.8831 199.06)'
``` 

And when round-tripping, it is the same:

```py
>>> c = colorcss("lch(100% -50 10)")
>>> c1 = c.convert("lab").convert("lch")
>>> c1.fit_gamut("srgb")
>>> c1.to_string()
'lch(97.977% 9.8831 199.06)'
```

Hopefully, this helps. I am no color expert, but I wanted to report this to you guys in case it was a bug 🙂. Or maybe this is completely expected or is undefined behavior.

**Comment by tabatkins** [comment]
A negative chroma is an error case, right? It sounds like we should just be clamping that to 0 before using it.

**Comment by facelessuser** [comment]
The current library seems to consider both Lab and Lch as always "in gamut". But I agree that it would seem that this *should* be clamped, at least when outputting a final value, I'm not as sure when dealing with conversion as this is not my area of expertise.

**Comment by LeaVerou** [comment]
Indeed, I'd classify this as a bug.

**Comment by svgeesus** [comment]
OK so now I am clamping any negative Chroma to zero. I also check for NaN Hue and arbitrarily set it to zero, which is probably fine since in general the Chroma will be near-zero in that case.

```js
to: {
		lab (LCH) {
			// Convert from polar form
			let [Lightness, Chroma, Hue] = LCH;
			// Clamp any negative Chroma
			if (Chroma < 0) {
				Chroma = 0;
			};
			// Deal with NaN Hue
			if (isNaN(Hue)) {
				Hue = 0;
			}
			return [
				Lightness, // L is still L
				Chroma * Math.cos(Hue * Math.PI / 180), // a
				Chroma * Math.sin(Hue * Math.PI / 180)  // b
			];
		}
	},
```

**Comment by svgeesus** [comment]
> Now, I implemented the deltaE2000 directly from http://www2.ece.rochester.edu/~gsharma/ciede2000/ciede2000noteCRNA.pdf, so I was very literal in my translation to code. 

Excellent. I did too. Many online calculators git this wrong in small ways. I also put all the Sharma dataset into the [color.js deltaE tests](https://colorjs.io/tests/delta.html) as another sanity check.

**Comment by facelessuser** [comment]
This helps when When converting from Lch to Lab, but are we still going to hit a deltaE issue as the Chroma is grabbed directly from Lch without any adjustment? Or is this resolved somehow before we get to this point? It is unclear looking at the code.

```js
	let [L1, a1, b1] = color.lab;
	let C1 = color.chroma;
	let [L2, a2, b2] = sample.lab;
	let C2 = sample.chroma;
```

**Comment by svgeesus** [comment]
> You guys seem to just take the chroma from the already calculated Lch value, which I am assuming is coming out as negative. 

I don't see how a calculated Chroma could be negative

```js
return [
	L, // L is still L
	Math.sqrt(a ** 2 + b ** 2), // Chroma
	angles.constrain(hue) // Hue, in degrees [0 to 360)
	];
```
but user-entered coordinates could be.

**Comment by svgeesus** [comment]
I'm unsure whether to try and trap user input on LCH, or to do the check again in deltaE2000

**Comment by facelessuser** [comment]
Calculated probably couldn't be, but in the case I originally posted, chroma was user defined.

Not sure if the user input should always be clammped as zero chroma or not as it doesn't seem to be helpful. I'm not sure preserving the negative helps with translation to other colors either. At the very least, if deltaE2000 calculated chroma from `a` and `b`, you'd at least get a sane positive chroma, even if the value may be a little off as zero should probably be used. At least that is my impression.

I could be wrong though, this is just my amateur analysis 🙁 .

**Comment by svgeesus** [comment]
In general,avoiding clamping slightly-out-of-range values is a good thing. For example, CIE XYZ is defined to be all-positive, so implementations often did clamping to non-negative. But then it turn out if you measure colors under one illuminant and then chromatically adapt to a different one you can end up with small negative values. So te current recommendation is not to clamp, to avoid cumulative round-trip errors.

**Comment by facelessuser** [comment]
Okay, so it sounds like a negative chroma input by the user is to be accepted as an undefined case. Translation via a roundtrip conversion through Lab will correct it. DeltaE2000 will continue to assume chroma is correct and use it instead of recalculating it from the current Lab space?

**Comment by svgeesus** [comment]
> DeltaE2000 will continue to assume chroma is correct and use it instead of recalculating it from the current Lab space?

No, I think it should correct it too.

**Comment by facelessuser** [comment]
> No, I think it should correct it too.

Okay, that makes sense. Was just making sure I was following the direction. I think in the past month I've learned more about colors than I planned to. It is a surprisingly complex area 🙂.

**Comment by svgeesus** [comment]
[fix negative Chroma in LCH to Lab](https://github.com/LeaVerou/color.js/commit/bad9908575bf91b1b9a1401a770f30db8264b86d)
[fix negative Chroma in LCH-based distance metrics](https://github.com/LeaVerou/color.js/commit/c5532dc0e3fdf83ed9ddbdb519492db9af7574aa)

**Comment by svgeesus** [comment]
> . It is a surprisingly complex area 

💯
