### ISSUE TITLE
HSL to HWB conversion when saturation is 0 or lightness is 100

### ISSUE THREAD

**Issue by facelessuser** [LeaVerou/color.js#54]
Is this really the expected output from HSL to HWB when saturation is zero?

Input:

```js
new Color("hsl(0, 0, 100%)").to("hwb");
```

Output:

```
hwb(137.3 100% 0%)
```

It seems to default to `137.3` for hue if saturation is `0` and/or lightness is `100`. The one exception is when saturation is `0` and lightness is `0`, then we get a hue of `0`.

If saturation is not `0` and lightness is not `0` (or they are both `0`) we get a hue of `0`.

```js
new Color("hsl(0, 0, 0%)").to("hwb");
```

Output:

```
hwb(0 0% 100%)
```

And:

```js
new Color("hsl(0, 1%, 99%)").to("hwb");
```

Output:

```
hwb(0 99% 1%)
```

I'd try to debug this more, but it is difficult to install and play with this in node. Maybe I'm importing it wrong or maybe this library is only meant to be played with directly in a browser?

**Comment by LeaVerou** [comment]
Ah, we handle achromatic hue specially, but I suspect we forgot hwb.

Could you please open a separate issue with more details about the node issues? It should definitely be possible to use this in node (except for parsing color keywords and hex atm, which uses the DOM, but that will change soon)

**Comment by svgeesus** [comment]
So first I think we should incorporate [the HWB achromatic test [as reported here on CSS Color 4](https://github.com/w3c/csswg-drafts/issues/5531)

**Comment by svgeesus** [comment]
Achromatic check [was added](https://github.com/LeaVerou/color.js/commit/9819506f3f6b018e6bddaddf853af30b4b5944fe#diff-86d5493889535d695ba80e379cfc1d372a68b2aabb2e5a19c19ffdced7dcc5fb)

```js
new Color("hsl(0, 0, 100%)").to("hwb");
```

now gives the expected result

![image](https://user-images.githubusercontent.com/2506926/101024495-d45ccb00-357c-11eb-82b7-c2d593f9c237.png)
