### ISSUE TITLE
How to run and test locally?

### ISSUE THREAD

**Issue by facelessuser** [LeaVerou/color.js#55]
This issue is created in response to https://github.com/LeaVerou/color.js/issues/54#issuecomment-703844158.

I'm not sure it is a bug as much as maybe a question. How can one quickly run and evaluate this project locally? Coding up a web environment is surely possible, and one could import the code and test, but when it mentioned you could install via npm, I found that an attractive option as I was looking more to debug issue #50 

1. Tried to install via the documentation's recommendation for node, and the package isn't found in the registry, so maybe that is outdated.

2. Tried to install by using the git repo, seemed to work, but couldn't figure out how to import it. Seems it is an ESM module as it complained about `import`? Struggled to figure out when I couldn't load it. Googled some things and tried to load it as an ESM module, but only ran into other complaints.

Maybe all that is needed is a little documentation for the less knowledgable like me 🙂.

I'm on node.js v14.4.0.

**Comment by LeaVerou** [comment]
Ah, I see what's going on here: Because the library is pre-release, we never published on npm, since you need a release for that. 🤦🏽‍♀️
We could make a release with a 0.0.x version or something, just so we can publish on npm. @svgeesus are you ok with that? 

We'll need to find a good package name too. All the following are taken 😕

http://npmjs.com/package/color
https://www.npmjs.com/package/color-js
https://www.npmjs.com/package/color.js
https://www.npmjs.com/package/colorjs

Maybe https://www.npmjs.com/package/colorjs.io or Maybe https://www.npmjs.com/package/colorjsio (which is what's in the docs)

Regarding import: yes, it's an ESM module, so you need to import it with a regular `import` statement, not `require()` (which also means you need Node v13.2 or later)

**Comment by facelessuser** [comment]
> Ah, I see what's going on here: Because the library is pre-release, we never published on npm, since you need a release for that

I completely understand if it isn't ready. The docs mentioned it was still a prerelease, I assumed, incorrectly, that the prereleases were available as the docs mentioned you could use node.

> Regarding import: yes, it's an ESM module, so you need to import it with a regular import statement, not require() (which also means you need Node v13.2 or later)

This was also the tricky part. So I figured out this much and tried to import it with `import`, but it complained about that. Googling led me to someone saying you should add `"type": "module"` to the package JSON, which then gave me new issues about trying to use an ESM module. It is unclear to me how you can get the package running as a node module. With all of that said, maybe it is an issue with the latest node, I'm not sure as I haven't tried out other node releases.

I also realize you guys may not be testing in node, which is understandable. Even if there was a quick way just to get it up and running locally, like run a playground locally, that would be nice for anyone who stumbles upon this project and figures they want to try to tinker with it to try and help solve bugs.

I also realize this may not be a priority at this early stage either.

**Comment by LeaVerou** [comment]
> I completely understand if it isn't ready. The docs mentioned it was still a prerelease, I assumed, incorrectly, that the prereleases were available as the docs mentioned you could use node.

Your assumption is correct, we *should* put it on npm! Any thoughts on the package name?

> Googling led me to someone saying you should add "type": "module" to the package JSON, which then gave me new issues about trying to use an ESM module.

Do you by any chance remember what these were?

> I also realize you guys may not be testing in node, which is understandable. 

It's true we haven't been, but we certainly want it to work on Node and are more than willing to fix any issues!

I was under the impression ESM were supported properly in Node. If not, we can just export CJS as well, since we use Rollup anyway.

**Comment by facelessuser** [comment]
Yeah, even adding `"type": "module"` still complianed.

```
➜  colors node
Welcome to Node.js v14.4.0.
Type ".help" for more information.
> import Color from "color.js"
import Color from "color.js"
^^^^^^

Uncaught SyntaxError: Cannot use import statement outside a module
```

But then I read somewhere you have to use some other package for loading ESM, so I tried that (maybe incorrectly):

```
➜  colors node -r @std/esm
Welcome to Node.js v14.4.0.
Type ".help" for more information.
> import Color from "color.js"
/Users/facelessuser/Code/colors/node_modules/color.js/color.js:1
Uncaught:
Error [ERR_REQUIRE_ESM]: Must opt-in @std/esm@0.26.0 to load ES Module: /Users/facelessuser/Code/colors/node_modules/color.js/color.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1216:13)
    at Object.qe (/Users/facelessuser/Code/colors/node_modules/@std/esm/esm.js:1)
    at Object.f (/Users/facelessuser/Code/colors/node_modules/@std/esm/esm.js:1)
    at Object.p (/Users/facelessuser/Code/colors/node_modules/@std/esm/esm.js:1)
    at Object.<anonymous> (/Users/facelessuser/Code/colors/node_modules/@std/esm/esm.js:1)
    at /Users/facelessuser/Code/colors/node_modules/@std/esm/esm.js:1
    at /Users/facelessuser/Code/colors/node_modules/@std/esm/esm.js:1
    at module.exports.t.a (/Users/facelessuser/Code/colors/node_modules/@std/esm/esm.js:1)
    at module.exports.t.a (/Users/facelessuser/Code/colors/node_modules/@std/esm/esm.js:1)
    at module.exports.t.a (/Users/facelessuser/Code/colors/node_modules/@std/esm/esm.js:1) {
  code: 'ERR_REQUIRE_ESM'
```

This is the part that is confusing to me. How are esm modules supposed to be run in node? Cjs is fine as well and sounds like an easier approach. Esm is fine to, I just can't figure out how to run it 🙃 .

**Comment by facelessuser** [comment]
> Any thoughts on the package name?

Names are tough. I was the type of kid that named my stuffed animals with unimaginative names. I had a bear called Bear and dog called Dog. I'm probably not the best person for names.

With that said, I did a search on npm. It seems `color`, `colors`, `colour`, `colours` are all taken in various forms with `-js` and `.js`. Though, you could maybe snag `colours-js` 🤷.

It seems you already have a colorjs.io domain so sticking with something similar is probably ideal. Maybe `css-color.js` or `css.color.js` at least for the package name as there is a strong link to CSS and this project. 

If you were okay moving away from "color.js", also, maybe something like `chromaticy`?

That's probably all I have, though you can take Dog or Bear as well 🙂.

**Comment by svgeesus** [comment]
>  @svgeesus are you ok with that?

Totally. Enough people know about this (I demonstrated it at the ICC meeting in June for example, and it is linked from their Open Source software page) that we really should do a release.

There are bugs, but it will be a pre-release; and I think there are more bugs in the color notebook functionality than the actual color conversion and manipulation code.

**Comment by kripod** [comment]
I would be curious to try this library, as it seems to be amongst the best in its class.

Are there any updates regarding an npm (pre)release? Thank you for the assistance in advance! 😊

**Comment by LeaVerou** [comment]
Thanks for the nudge! Just published it: https://www.npmjs.com/package/colorjs.io

Let us know how it goes!

Btw, if you're using it to parse CSS colors, please note that hex colors and color keywords are not yet parsed in Node (as they depend on browser APIs for parsing). We do plan to change that.

**Comment by kripod** [comment]
Congratulations on the release! 🚀

Oh well, thank you for the disclaimer! I just wanted to use that particular functionality in Node (inside a `tailwind.config.js` file) 😅

Formerly, I was using something like `"rgba(#121118, 0.32)"` along with [postcss-hexrgba](https://github.com/seaneking/postcss-hexrgba), but it isn't standard and I'd like to get rid of my custom PostCSS config for a Next.js project, making it ready for the [upcoming Tailwind integration](https://github.com/vercel/next.js/discussions/20030).

I also considered alternatives like the [`color` package](https://github.com/Qix-/color) and [Convert Colors](https://github.com/jonathantneal/convert-colors), but like your ideas the most. Keep up with the great work, I'm eagerly waiting to try it out once it supports HEX codes in Node out of the box 😊

**Comment by LeaVerou** [comment]
Was it just hex colors you wanted to convert or color keywords too?

**Comment by kripod** [comment]
Just hex colors, I’m not using color keywords anywhere.

**Comment by LeaVerou** [comment]
@kripod Ok, that nudged me to finally get around to it, [just pushed a change](https://github.com/LeaVerou/color.js/commit/2e0d6f0fd63baebc7702ffe04822b01eb1021d4f) that routes hex colors through color.js instead of the browser DOM. Please try it out and let us know how it went! :)

**Comment by kripod** [comment]
Wonderful, thank you! 🙌

I’ll let you know how it went after work.

**Comment by kripod** [comment]
Unfortunately, it seems that the current npm version doesn't incorporate the changes for hex support yet. I'll be able to try the functionality once hex support in Node is available. Thank you in advance! 🙏

**Comment by LeaVerou** [comment]
You can install the latest branch of an npm module via `@latest`, see https://docs.npmjs.com/try-the-latest-stable-version-of-npm

**Comment by LeaVerou** [comment]
Huh, I thought there was a way to install the latest version of an npm module, even if it's unreleased, but I can't find it. So I released another version. :)

**Comment by kripod** [comment]
Unfortunately, it seems that I cannot use it in a `tailwind.config.js` file, due to the fact that there isn't a CommonJS distribution available:

<img width="650" alt="image" src="https://user-images.githubusercontent.com/14854048/101813530-1e195880-3b1d-11eb-9ebf-db249be8b96e.png">

While I know that `"type": "module"` could be added inside my project's `package.json` file, the ecosystem doesn't seem to be ready for that big leap as of now, especially when using only Node 12 (for deployment on Vercel).

**Comment by LeaVerou** [comment]
We do use Rollup to export bundles in different module systems, but then you lose the granularity…

**Comment by kripod** [comment]
Unfortunately, it seems that [no CommonJS modules are produced](https://github.com/LeaVerou/color.js/blob/c987b76470a0672206807b98318de5a81195bf9c/gulpfile.js#L167-L176), limiting adoption for several Node versions in use. While I hope that the ESM situation will become much better in the upcoming 2 years, it would be great to adopt this fantastic library without migrating from CommonJS (in config files) first.

**Comment by LeaVerou** [comment]
I know but that can be easily fixed. I just pushed a commit that produces CJS too. What I was saying is, the bundles contain all modules, so you lose the granularity.

**Comment by kripod** [comment]
Oh, I see, thank you! Cannot wait to try a new npm release with CommonJS support, thank you for adding it! 😊

The loss of granularity isn’t a dealbreaker for Node in my opinion.

**Comment by LeaVerou** [comment]
Also, apparently you can `npm install` from Github, which installs the latest commit: https://remarkablemark.org/blog/2016/09/19/npm-install-from-github/

**Comment by kripod** [comment]
Thank you, I know about that, but no bundling happens then, so it isn’t a good experience to use out of the box… 😕

**Comment by LeaVerou** [comment]
Ah, I see. Ok, I'll release a new version

**Comment by LeaVerou** [comment]
Done!

**Comment by kripod** [comment]
Thanks, I appreciate how fast you're delivering these updates.

I tried using the following functionality with Node v14.15.0, but it threw an error on me:

```js
const { default: Color } = require("colorjs.io/dist/color.cjs");

console.log(new Color("#ff0000").set({ alpha: 0.5 }).toString());
```

Am I doing something wrong?

_(As a side note, I think the CommonJS module should be exported from the `package.json` `main` field, while the ESM build should be published under `module`. Both versions could be defined as [`exports`, serving hints](https://nodejs.org/api/packages.html#packages_package_entry_points) to Node and bundlers)_

**Comment by facelessuser** [comment]
To be specific, we are getting the following error:

```
Uncaught ReferenceError: self is not defined
    at Color$1.get [as srgb] (/Users/facelessuser/colors/node_modules/colorjs.io/dist/color.cjs.js:1042:5)
```

Basically, there are a couple of references to `self` that should be `this`. I assume a mixup due to coding in different languages. I know I run into this sometimes when I do JS as I also code in Python.

Two instances are found here:

- https://github.com/LeaVerou/color.js/blob/master/src/color.js#L482
- https://github.com/LeaVerou/color.js/blob/master/src/color.js#L852

So much easier to debug now that I can run it locally 🙂.

**Comment by facelessuser** [comment]
Changing the above, mentioned lines fixes @kripod's issues:

```js
> const { default: Color } = require("colorjs.io/dist/color.cjs");
undefined
> console.log(new Color("#ff0000").set({ alpha: 0.5 }).toString());
rgb(100% 0% 0% / 0.5)
undefined
```

**Comment by LeaVerou** [comment]
Thank you both! I will fix it tomorrow (it's currently 2am). Or will merge a PR, if anyone wants to submit one :)

**Comment by facelessuser** [comment]
Done: https://github.com/LeaVerou/color.js/pull/61

**Comment by kripod** [comment]
Great job, @facelessuser! 🙌

I've also done my part with conditional `package.json` exports.

**Comment by Artoria2e5** [comment]
The lack of CommonJS export is making my life quite a bit harder in the RunKit notebook. May I ask for a [`esm`](https://github.com/standard-things/esm) wrapper so it becomes usable from cjs?

**Comment by LeaVerou** [comment]
Is this resolved or are there outstanding issues?

**Comment by facelessuser** [comment]
From my perspective, and the issues I was having, this is resolved. Any other issues should probably be handled as separate issues.

**Comment by LeaVerou** [comment]
I believe @Artoria2e5's issue has been resolved too, so I'm gonna close this.
