### ISSUE TITLE
Naming: Color Spaces should be called color models

### ISSUE THREAD

**Issue by meodai** [LeaVerou/color.js#59]
https://colorjs.io/docs/spaces.html

Looks like the docs page about the spaces is a bit of a mixed bag when it comes to the terminology:

- A color space is a set of color that can be show by a certain device, screen or programm. Examples: Adobe RGB, sRGB, 
- A color model is a mathematical model to describe color is that given space.

More reading: https://programmingdesignsystems.com/color/color-models-and-color-spaces/index.html
pixar made a great video on the subject.

Hope that helps, the wording confused me at first.

PS: great library!

**Comment by svgeesus** [comment]
I agree these terms can be confusing, and they are often used loosely.

> A color space is a set of color that can be show by a certain device, screen or programm. 

There is no requirement that a given color space has to be displayable. For example, CE XYZ and CIE Lab are both unbounded and can represent any physical color. ProPhoto RGB has non-physical primaries (outside the spectral locus) and thus by definition large parts of that color space do not correspond to physically realizable colors.

> Adobe RGB, sRGB

These also have mathematical models (well, a transfer function to go to and from the linear-light representation). From wikipedia:

> For example, Adobe RGB and sRGB are two different absolute color spaces, both based on the RGB color model.
> https://en.wikipedia.org/wiki/Color_space

So the underlying color _model_ here is additive light. All of the color spaced implemented in color.js inter-relate through that underlying model, represented as CIE XYZ with a 2 degree standard observer.

A color _space_, though, implies a three (or more) dimensional representation of color. This then leads on to the concept of color distance between two points in that space, which ideally relates directly to how similar or dissimilar a pair of colors seem. And that in turn is used for generating ranges or steps of color, or performing gamut mapping between one space and another.

Is that clearer?

**Comment by meodai** [comment]
@svgeesus oh thanks, I thought it was clear to me before I read your answer :D 

Thanks for this explanation.
I did not know that there are sRGB and adobeRGB models as well. I might have to need.

I don't want to nitpick here, But would it not be safer to call the section in the docs color models,
since HSL, HWB, HSV are definitely not spaces.

I was confused at first because of that. But it probably does not matter too much, since most people say "color space" for the model and the actual space. 

Thanks again.

**Comment by Crissov** [comment]
like so?

- RGB: color model, additive
  - sRGB: color space (with specific gamut)
    - HSL: color **???** – color space representation/transformation/…
      - `hsl(<angle>, <percentage>, <percentage>)`: color notation
    - HSB = HSV
    - HSI
    - HWB
    - sRGB cartesian cube 
      - `rgb(<percentage>, <percentage>, <percentage>)`
      - `rgb(<float>, <float>, <float>)`
    - sRGB cartesian cube, 4bit
      - `#<hexdigit>{3}`
      - VGA named colors ````````
    - sRGB cartesian cube, 8bit
      - `#(<hexdigit>{2}){3}`
      - `rgb(<int>, <int>, <int>)`
      - X11 named colors(?)
  - CIE 1931 RGB (2°): reference/canonical color space
    - CIEXYZ: reference/canonical color space representation/…
    - CIELAB
    - …
  - …
- CMYK: color model, subtractive 
…

**Comment by meodai** [comment]
@Crissov That would be very explicit, but also very educational.
