### ISSUE TITLE
Round trip of sRGB seems wrong

### ISSUE THREAD

**Issue by facelessuser** [LeaVerou/color.js#64]
```
let color = new Color("color(srgb -0.3 0.5 1)").to('xyz').to('srgb')
```

result

```
[-0.41,0.5,1]
```

Maybe I'm missing what this change is trying to solve, but this doesn't seem right and seems to be causing the problem: https://github.com/LeaVerou/color.js/commit/efe60a84ee567e3fb7b8fb7343c45bac89de3085.

Without the change, it would round trip properly to `[-0.3,0.5,1]`.

**Comment by facelessuser** [comment]
Looking at things closer, I think I understand what was intended, but I think it doesn't need to happen in sRGB.

In sRGB, you are never given a negative value that goes through `pow`, as the algorithm specifically checks this and sends it down the other route. So the above change is only breaking the non-pow route.

In think this was trying to apply the same trick done in `a98-rgb`, but it isn't needed in `srgb`. in `a98-rgb` there is actually a real risk of a negative number going through `pow`, so val must be an absolute value and the sign copied to the result. And you guys already do this perfectly.

```js
    {
		return RGB.map(val => Math.pow(Math.abs(val), 563/256)*Math.sign(val));
	},
	toGamma(RGB) {
		return RGB.map(val => Math.pow(Math.abs(val), 256/563)*Math.sign(val));
	},
```

It appears to me that https://github.com/LeaVerou/color.js/commit/efe60a84ee567e3fb7b8fb7343c45bac89de3085 is fixing an issue that does not exist, or at least is fixing is attempting to fix something that isn't obvious but is going about it improperly.

**Comment by facelessuser** [comment]
I see now that the intent was to completely mirror the behavior so that near-zero negative numbers went down the non-pow route and negative values further from zero own the pow route. The problem is that the algorithm is no longer a mirror image, but if you make this change it will be (notice the added parenthesis):

```js
if (abs > 0.0031308) {
	return sign * (1.055 * Math.pow(abs, 1/2.4) - 0.055);
}
```

**Comment by svgeesus** [comment]
Oh wow, yes that is indeed what was wanted.

The intent was to completely mirror the transfer function below zero. This is because, for gamma-encoded RGB spaces, this is what current graphics hardware does with negative values, and is what Canvas is adopting as well.

**Comment by facelessuser** [comment]
Thanks for the explanation! It is good to know also that this isn't something that just CSS is adopting.
