### ISSUE TITLE
Recent change to REC.2020 seems to have a decimal place wrong

### ISSUE THREAD

**Issue by facelessuser** [LeaVerou/color.js#67]
https://github.com/LeaVerou/color.js/commit/1c63d9cf3a17fe28821d8f96507b3f32fe952ca2 Seems to break round tripping of REC.2020. After investigating and examining the referenced table 4 in https://www.itu.int/dms_pubrec/itu-r/rec/bt/R-REC-BT.2020-2-201510-I!!PDF-E.pdf, it seems the constant that was described is `0.45` not `4.5`.

<img width="268" alt="Screen Shot 2021-01-29 at 11 24 14 AM" src="https://user-images.githubusercontent.com/1055125/106312938-aadeb980-6224-11eb-91aa-f73214bf07bf.png">

This change seems to fix the issue for me locally. I will issue a pull request if it isn't addressed before I get to it.

**Comment by facelessuser** [comment]
I was about to submit a pull, but it looks like it got fixed before I had a chance via  https://github.com/LeaVerou/color.js/commit/3c24174ef2c1ef61992e60104b99b4873486a92a. 🙂

**Comment by svgeesus** [comment]
Yes, I fixed my stupid error very quickly 😳
