### ISSUE TITLE
jzczhz -> srgb conversion error

### ISSUE THREAD

**Issue by cdosborn** [LeaVerou/color.js#69]
The following color, `new Color("jzczhz", [0.19, 0, 226])` should produce a gray as it has no chroma. However, the color has quite a bit of chroma:
![2021-02-03-113900_354x277_scrot](https://user-images.githubusercontent.com/3847314/106779005-8adc3b00-6614-11eb-9932-06ff8ec6b3a5.png)

I also checked that the color is in `srgb` space.

**Comment by svgeesus** [comment]
Hmm. Yes, it does. And the hue angle doesn't matter, it is all the same color.

Worse, [`jzazbz(0.19 0 0)`](https://colorjs.io/apps/convert/?color=color(jzczhz%200.19%200%200)&precision=5) which should be a neutral, has the same color.

Thanks for the bug report, will investigate.

**Comment by svgeesus** [comment]
An sRGB neutral, such as [`#777`](https://colorjs.io/apps/convert/?color=%23777&precision=5) is coming out as `jzazbz(0.11102 -0.005 -0.021)` when both `az` and `bz` should be zero.

**Comment by svgeesus** [comment]
So if I convert ` jzazbz(0.19 0 0)` to Absolute, D65 XYZ using colorjs I get [130.4109950375476, 137.11749630300756, 149.18763369878602].

The same conversion with the reference matlab code (by the authors of Jzazbz) 

>> JzAzBz ([0.19 0 0],"r")
ans =
   130.41   137.12   149.19

which is the same to two decimal places (five significant figures). So I'm going to examine the steps Absolute D65 XYZ to relative XYZ (with the whitepoint depending on the from and to whitepoints, Bradford chromatic adaptation applied as needed, which it isn't for Jzazbz to sRGB as both have a D65 white.

**Comment by svgeesus** [comment]
Aha. So normally, if you convert some RGB space to XYZ, it is reported as a XYZ relative to D50 white. A Bradford CA is used to go from D65 to D50.

My implementation of an absolute XYZ with D65 white (as used by ICtCp and Jzazbz) therefore first did a Bradford CA from D50 to D60, then scaled all the values by 203 cd/m^2 (which is the recommended luminance in a PQ HDR system for media white, from ITU Rpt BT.2408).

However, the automatic to/from arbitrary colorspace code, which first tries to find a path to and from relative XYZ, checks the whitepoint of the source and destination, and only does CA if they are different.

Which means that, going from a D65 RGB space like sRGB (well, most of them, except for ProPhoto) to a D65 absolute space like Jzazbz or ICtCp, the CA to D50 was sipped as un-needed.Then, my absolute D65 code was doing the D50 to D65 **on values that were already relative to D65**.

Removing that unnecessary, hard coded  CA fixed the problem.

**Comment by svgeesus** [comment]
[`color(jzczhz 0.19 0 0)`](https://colorjs.io/apps/convert/?color=color(jzczhz%200.19%200%200)&precision=5) is a nice neutral gray now.

**Comment by cdosborn** [comment]
Super!
