### ISSUE TITLE
Color mixing creates surprising (wrong?) results

### ISSUE THREAD

**Issue by ChristianMayer** [LeaVerou/color.js#78]
Test case:
```
r = new Color('red');            // r.toString() = "rgb(100% 0% 0%)"
g = new Color('srgb',[0,1,0]);   // g.toString() = "rgb(0% 100% 0%)"

r.mix(g,0.5).toString();
```
Result: `"rgb(78.613% 67.262% 0%)"`
Expected result: `"rgb(100% 100% 0%)"`

**Comment by facelessuser** [comment]
What is being claimed as expected (`"rgb(100% 100% 0%)"`) is not really correct.  If you mix a channel of 100% with a channel of 0%, you would get something in the middle, not 100%. Instead, you'd get 50%, but only if you are mixing in the `srgb` space:

```js
> new Color('red').mix("color(srgb 0 1 0)", {space: "srgb"}).toString()
'rgb(50% 50% 0%)'
```

Keep in mind, the documentation states the default color space is `lab` if one is not defined:

```js
> new Color('red').mix("color(srgb 0 1 0)", {space: "lab"}).toString()
'rgb(78.613% 67.262% 0%)'
```

Anyways, what is more, you are not mixing paint colors here, but interpolating between two colors and finding a color in the middle. Essentially, it is like drawing a line in the given color space that passes between the colors in the specified color space and then picking a point between them. Depending on the color space, the results can be quite different.

Hopefully, that helps.

**Comment by ChristianMayer** [comment]
Adding `{space: "srgb"}` was the relevant information, thanks!
