### ISSUE TITLE
Contrast ratio seems wrong

### ISSUE THREAD

**Issue by facelessuser** [LeaVerou/color.js#82]
It seems that Color.js, when calculating relative luminance, uses the Y coordinate of the XYZ color space, but that XYZ color space uses D50.

```js
> let color = new Color("#343e58").contrast("#ca6c87");
3.095
```

This doesn't seem to match every other implementation. For instance, D3 has a whole page explaining contrast and goes through all the math: https://observablehq.com/@mbostock/wcag-contrast-ratio. They get `3.039602551762186`.

This seems to align closer to an XYZ color space using D65. I made an adjustment to my local library to use D65, and get something that aligns much better with every other WCAG contrast ration implementation.

```py
>>> Color("#343e58").contrast("#ca6c87")
3.039797627037577
```

Is this a mistake/bug in color.js?  Or is this a new direction that is purposefully being taken? It is very unclear as it states it calculates WCAG 2.1 color contrast, but it seems it actually does not. Or maybe I'm just confused?

**Comment by LeaVerou** [comment]
I think it's a bug, thank you for spotting that! PR welcome!

**Comment by svgeesus** [comment]
Yes, WCAG 2.0 is sRGB only and thus (by inference) is adapted to D65.
