### ISSUE TITLE
Delta E 2000  bugs

### ISSUE THREAD

**Issue by facelessuser** [LeaVerou/color.js#84]
Reference: http://www2.ece.rochester.edu/~gsharma/ciede2000/ciede2000noteCRNA.pdf

There seem to be some issues in the algorithm for Delta E 2000. Consider the following:

<img width="378" alt="Screen Shot 2021-03-30 at 12 34 13 AM" src="https://user-images.githubusercontent.com/1055125/112944200-c153a500-90ef-11eb-936f-b4229fb5dad5.png">

It appears instead of `Cdash1 * Cdash2 == 0`, each `Cdash` is been compared against zero individually.

```js
	if (Cdash1 == 0 && Cdash2 == 0) {
		Δh = 0;
	}
	else if (habs <= 180) {
		Δh = hdiff;
	}
	else if (hdiff > 180) {
		Δh = hdiff - 360;
	}
	else if (hdiff < -180) {
		Δh = hdiff + 360;
	}
	else {
		console.log("the unthinkable has happened");
	}
```

This also occurs later here:

```js
	// Compensate for non-linearity in the blue region of Lab.
	// Four possibilities for hue weighting factor,
	// depending on the angles, to get the correct sign
	let hdash;
	if (Cdash1 == 0 && Cdash2 == 0) {
		hdash = hsum;   // which should be zero
	}
	else if (habs <= 180) {
		hdash = hsum / 2;
	}
	else if (hsum < 360) {
		hdash = (hsum + 360) / 2;
	}
	else {
		hdash = (hsum - 360) / 2;
	}
```

The second issue is also subtle. Earlier, habs was calculated as:

```js
	// Hue difference, getting the sign correct
	let hdiff = h2 - h1;
    ...
	let habs = Math.abs(hdiff);
```

But it is reused when calculating `hdash`, but it should not be. Instead of `Math.abs(h2 - h1)`, the algorithm actually calls for `Math.abs(h1 - h2)`.

<img width="339" alt="Screen Shot 2021-03-30 at 12 41 03 AM" src="https://user-images.githubusercontent.com/1055125/112944852-a46ba180-90f0-11eb-8afa-6e5b46d936f4.png">

Ultimately, I think the following changes should be made:

```diff
--- a/src/deltaE/deltaE2000.js
+++ b/src/deltaE/deltaE2000.js
@@ -84,7 +84,7 @@ Color.prototype.deltaE2000 = function (sample, {kL = 1, kC = 1, kH = 1} = {}) {
 	let habs = Math.abs(hdiff);
 	let Δh;
 
-	if (Cdash1 == 0 && Cdash2 == 0) {
+	if (Cdash1 * Cdash2 == 0) {
 		Δh = 0;
 	}
 	else if (habs <= 180) {
@@ -112,10 +112,10 @@ Color.prototype.deltaE2000 = function (sample, {kL = 1, kC = 1, kH = 1} = {}) {
 	// Four possibilities for hue weighting factor,
 	// depending on the angles, to get the correct sign
 	let hdash;
-	if (Cdash1 == 0 && Cdash2 == 0) {
+	if (Cdash1 * Cdash2 == 0) {
 		hdash = hsum;   // which should be zero
 	}
-	else if (habs <= 180) {
+	else if (Math.abs(h1 - h2) <= 180) {
 		hdash = hsum / 2;
 	}
 	else if (hsum < 360) {
```

**Comment by facelessuser** [comment]
I've created a pull request to fix the issue. Feel free to close if I am in error.

**Comment by svgeesus** [comment]
On the first point, yes! `(Cdash1 * Cdash2 == 0)` is correct.

Sadly, although the [deltaE tests](https://colorjs.io/tests/delta.html) include all the Sharma examples, there isn't a specific test to check eqn.10 is implemented correctly.

On the second point, the change is harmless and may be slightly better from a documentation standpoint, but `abs(a-b) === abs(b-a)` so I don't think this makes any difference.

**Comment by danburzo** [comment]
Just a drive-by comment, but when either Chroma is zero, a whole lot of the color difference formula is nullified via delta_h / delta_H being zero. That's why the change ultimately makes no practical difference; in reality, an optimized implementation seems like it might be able to skip a whole lot of computation.

**Comment by facelessuser** [comment]
> It seems the mathematical representation of the algorithm needs to take into account all possibilities at all steps, where actual code can take some liberties with skipping branches.

After extensive testing, that was my realization in the end.

> `abs(a-b) === abs(b-a)` 

Yep, this was my mistake. I don't know why I fixated on this one. For some reason, I was thinking if any of the values were negative, it would make a difference, but this is simply not true 🤦🏻.
