### ISSUE TITLE
Uncaught TypeError: Color is not a constructor

### ISSUE THREAD

**Issue by none511** [LeaVerou/color.js#98]
including the library in "classic way":
<script src="https://colorjs.io/dist/color.js"></script>
gives Uncaught TypeError: Color is not a constructor

**Comment by Artoria2e5** [comment]
Try using `Color.default`. It's a wrapped ESM thing now.

**Comment by LeaVerou** [comment]
Confirmed. [Testcase](data:text/html;charset=utf8,<script src="https://colorjs.io/dist/color.js"></script><script>new Color("purple")</script>)

Could possibly be a Rollup bug.

**Comment by LeaVerou** [comment]
> Try using `Color.default`. It's a transpiled ESM thing now. Tell me if it works or not, so I can do a doc PR accordingly.

Thanks for the workaround, but I consider this a bug on our end. People who want to use the IIFE bundle should not have to know or care about ESM, this looks like a leaky abstraction. If it's impossible to build it properly with Rollup, perhaps a custom Node script to transform the Rollup output might work. But it seems strange if Rollup can't do this.

**Comment by svgeesus** [comment]
This bit me again today

**Comment by gerardnico** [comment]
Me too. Thanks for the documentation !

**Comment by musagenius345** [comment]
Same thing happens with node REPL, I had to 

`const Color  = require('colorjs.io')
const colorObj = Color.default
let green = new colorObj('green')
`.
